In [ ]:
from google.colab import files

In [ ]:
from google.colab import drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import warnings

# Suprimir todos los warnings
warnings.filterwarnings('ignore')

# Ahora puedes ejecutar tu código sin que aparezcan mensajes de advertencia

warnings.filterwarnings('ignore', category=UserWarning)

In [ ]:
warnings.filterwarnings('ignore', category=UserWarning)

In [ ]:
# Configura pandas para mostrar todas las columnas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
def analizar_dataframe(df):
    # Calcula la cantidad de nulos por columna
    nulos_por_columna = df.isnull().sum()

    # Calcula la cantidad de datos duplicados
    duplicados = df.duplicated().sum()

    # Calcula la cantidad de filas con algún outlier
    # Para este caso, vamos a considerar un valor como outlier si está fuera del rango de 1.5 veces el rango intercuartil (IQR)
    # Solo consideramos las columnas numéricas para calcular los cuantiles
    columnas_numericas = df.select_dtypes(include=[np.number]).columns
    Q1 = df[columnas_numericas].quantile(0.25)
    Q3 = df[columnas_numericas].quantile(0.75)
    IQR = Q3 - Q1
    outliers = ((df[columnas_numericas] < (Q1 - 1.5 * IQR)) | (df[columnas_numericas] > (Q3 + 1.5 * IQR))).sum()

    return nulos_por_columna, duplicados, outliers

In [ ]:
ruta = '/content/drive/MyDrive/datasets_taxis/'

en_ruta = ruta + 'yellow_tripdata_2023-01.parquet'
feb_ruta = ruta + 'yellow_tripdata_2023-02.parquet'
mar_ruta = ruta + 'yellow_tripdata_2023-03.parquet'
ab_ruta = ruta + 'yellow_tripdata_2023-04.parquet'
may_ruta = ruta + 'yellow_tripdata_2023-05.parquet'
jun_ruta = ruta + 'yellow_tripdata_2023-06.parquet'
jul_ruta = ruta + 'yellow_tripdata_2023-07.parquet'
ag_ruta = ruta + 'yellow_tripdata_2023-08.parquet'
sep_ruta = ruta + 'yellow_tripdata_2023-09.parquet'

In [ ]:
# carga Santi

ruta = 'https://drive.google.com/drive/folders/1jiI8PFQKr02SEoIHBM6Fzcd6V00N1vei/'

en_ruta = ruta + 'yellow_tripdata_2023-01.parquet'
feb_ruta = ruta + 'yellow_tripdata_2023-02.parquet'
mar_ruta = ruta + 'yellow_tripdata_2023-03.parquet'
ab_ruta = ruta + 'yellow_tripdata_2023-04.parquet'
may_ruta = ruta + 'yellow_tripdata_2023-05.parquet'
jun_ruta = ruta + 'yellow_tripdata_2023-06.parquet'
jul_ruta = ruta + 'yellow_tripdata_2023-07.parquet'
ag_ruta = ruta + 'yellow_tripdata_2023-08.parquet'
sep_ruta = ruta + 'yellow_tripdata_2023-09.parquet'

In [ ]:
enero = pd.read_parquet(en_ruta)
febrero = pd.read_parquet(feb_ruta)
marzo = pd.read_parquet(mar_ruta)
abril = pd.read_parquet(ab_ruta)
mayo = pd.read_parquet(may_ruta)
junio = pd.read_parquet(jun_ruta)
julio = pd.read_parquet(jul_ruta)
agosto = pd.read_parquet(ag_ruta)
septiembre = pd.read_parquet(sep_ruta)

In [ ]:
ruta = '/content/drive/MyDrive/Datasets/'

alt_fuel_ruta = ruta + 'Alternative Fuel Vehicles US.csv'
alt_fuel = pd.read_csv(alt_fuel_ruta)

elec_alt_fuel_ruta = ruta + 'Electric and Alternative Fuel Charging Stations.csv'
elec_alt_fuel = pd.read_csv(elec_alt_fuel_ruta)

elec_car_ruta = ruta + 'ElectricCarData_Clean.csv'
elec_car_clean = pd.read_csv(elec_car_ruta)

elec_car_ruta_norm = ruta + 'ElectricCarData_Norm.csv'
elec_car_norm = pd.read_csv(elec_car_ruta_norm)

light_duty_ruta = ruta + 'Light Duty Vehicles.csv'
light_duty = pd.read_csv(light_duty_ruta)

vihicle_fuel_ruta = ruta + 'Light Duty Vehicles.csv'
vihicle_fuel = pd.read_csv(vihicle_fuel_ruta)

taxi_zones_ruta = ruta + 'taxi+_zone_lookup.csv'
taxi_zones_lookup = pd.read_csv(taxi_zones_ruta)

In [ ]:
# Aplica la función a cada uno de los nuevos dataframes

nulos_elec_alt_fuel, duplicados_elec_alt_fuel, outliers_elec_alt_fuel = analizar_dataframe(elec_alt_fuel)
nulos_elec_car_clean, duplicados_elec_car_clean, outliers_elec_car_clean = analizar_dataframe(elec_car_clean)
nulos_elec_car_norm, duplicados_elec_car_norm, outliers_elec_car_norm = analizar_dataframe(elec_car_norm)
nulos_light_duty, duplicados_light_duty, outliers_light_duty = analizar_dataframe(light_duty)
nulos_vihicle_fuel, duplicados_vihicle_fuel, outliers_vihicle_fuel = analizar_dataframe(vihicle_fuel)
nulos_taxi_zones_lookup, duplicados_taxi_zones_lookup, outliers_taxi_zones_lookup = analizar_dataframe(taxi_zones_lookup)


¡Claro! Aquí tienes una descripción de las columnas en tu conjunto de datos de enero:

VendorID:
Un identificador que representa la empresa de taxis.

tpep_pickup_datetime:
La fecha y hora en que el viaje fue iniciado.


tpep_dropoff_datetime:
La fecha y hora en que el viaje fue finalizado.


passenger_count:
El número de pasajeros en el viaje.


trip_distance:
La distancia total del viaje en millas.


RatecodeID:
El código de tarifa utilizado para calcular la tarifa del viaje.


store_and_fwd_flag:
Indica si el registro se almacenó y se reenvió al sistema central.


PULocationID:
El ID de ubicación donde se recogió al pasajero.


DOLocationID:
El ID de ubicación donde se dejó al pasajero.


payment_type:
El método de pago utilizado para el viaje.


fare_amount:
La tarifa base del viaje.


extra:
Montos adicionales agregados a la tarifa base.


mta_tax:
La tasa de impuesto de la Autoridad Metropolitana de Transporte.

tip_amount:
La propina dada al conductor.

tolls_amount:
La cantidad de peajes en el viaje.


improvement_surcharge:
Mejora de la tarifa.


total_amount:
El total pagado por el viaje, incluyendo tarifa, impuestos y propinas.


congestion_surcharge:
Sobrecargo por congestión.


airport_fee:
Tarifa de aeropuerto.


Esta descripción es general y basada en los nombres de las columnas. Si tienes información adicional sobre el conjunto de datos o el contexto específico, podría proporcionar una descripción más detallada o personalizada para cada columna.

In [ ]:
enero.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3066766 entries, 0 to 3066765
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int64(4), object(1)
memory usage: 444.6+ MB

In [ ]:
enero.head(5)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00

In [ ]:
enero.tail()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
3066761,2,2023-01-31 23:58:34,2023-02-01 00:12:33,NaN,3.05,NaN,None,107,48,0,15.80,0.0,0.5,3.96,0.0,1.0,23.76,NaN,NaN
3066762,2,2023-01-31 23:31:09,2023-01-31 23:50:36,NaN,5.80,NaN,None,112,75,0,22.43,0.0,0.5,2.64,0.0,1.0,29.07,NaN,NaN
3066763,2,2023-01-31 23:01:05,2023-01-31 23:25:36,NaN,4.67,NaN,None,114,239,0,17.61,0.0,0.5,5.32,0.0,1.0,26.93,NaN,NaN
3066764,2,2023-01-31 23:40:00,2023-01-31 23:53:00,NaN,3.15,NaN,None,230,79,0,18.15,0.0,0.5,4.43,0.0,1.0,26.58,NaN,NaN
3066765,2,2023-01-31 23:07:32,2023-01-31 23:21:56,NaN,2.85,NaN,None,262,143,0,15.97,0.0,0.5,2.00,0.0,1.0,21.97,NaN,NaN

In [ ]:
nulos_en, duplicados_en, outliers_en = analizar_dataframe(enero)
nulos_feb, duplicados_feb, outliers_feb = analizar_dataframe(febrero)
nulos_mar, duplicados_mar, outliers_mar = analizar_dataframe(marzo)
nulos_ab, duplicados_ab, outliers_ab = analizar_dataframe(abril)
nulos_may, duplicados_may, outliers_may = analizar_dataframe(mayo)
nulos_jun, duplicados_jun, outliers_jun = analizar_dataframe(junio)
nulos_jul, duplicados_jul, outliers_jul = analizar_dataframe(julio)
nulos_ag, duplicados_ag, outliers_ag = analizar_dataframe(agosto)
nulos_sep, duplicados_sep, outliers_sep = analizar_dataframe(septiembre)

In [ ]:
# Imprime los resultados
print("Viajes enero :")
print()
print("Nulos por columna:", nulos_en)
print()
print("Duplicados:", duplicados_en)
print()
print("Outliers:", outliers_en)
print()

Viajes enero :

Nulos por columna: VendorID                     0
tpep_pickup_datetime         0
tpep_dropoff_datetime        0
passenger_count          71743
trip_distance                0
RatecodeID               71743
store_and_fwd_flag       71743
PULocationID                 0
DOLocationID                 0
payment_type                 0
fare_amount                  0
extra                        0
mta_tax                      0
tip_amount                   0
tolls_amount                 0
improvement_surcharge        0
total_amount                 0
congestion_surcharge     71743
airport_fee              71743
dtype: int64

Duplicados: 0

Outliers: VendorID                      0
passenger_count          733623
trip_distance            390244
RatecodeID               155718
PULocationID                  0
DOLocationID                  0
payment_type             655304
fare_amount              325228
extra                     44706
mta_tax                   48704
tip_amount               221257
tolls_amount             226459
improvement_surcharge     31395
total_amount             371616
congestion_surcharge     250755
airport_fee              264567
dtype: int64

In [ ]:
febrero.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2913955 entries, 0 to 2913954
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 389.1+ MB

In [ ]:
febrero.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,1,2023-02-01 00:32:53,2023-02-01 00:34:34,2.0,0.30,1.0,N,142,163,2,4.4,3.50,0.5,0.0,0.0,1.0,9.40,2.5,0.00
1,2,2023-02-01 00:35:16,2023-02-01 00:35:30,1.0,0.00,1.0,N,71,71,4,-3.0,-1.00,-0.5,0.0,0.0,-1.0,-5.50,0.0,0.00
2,2,2023-02-01 00:35:16,2023-02-01 00:35:30,1.0,0.00,1.0,N,71,71,4,3.0,1.00,0.5,0.0,0.0,1.0,5.50,0.0,0.00
3,1,2023-02-01 00:29:33,2023-02-01 01:01:38,0.0,18.80,1.0,N,132,26,1,70.9,2.25,0.5,0.0,0.0,1.0,74.65,0.0,1.25
4,2,2023-02-01 00:12:28,2023-02-01 00:25:46,1.0,3.22,1.0,N,161,145,1,17.0,1.00,0.5,3.3,0.0,1.0,25.30,2.5,0.00

In [ ]:
febrero.tail()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
2913950,2,2023-02-28 23:46:00,2023-03-01 00:05:00,NaN,4.65,NaN,None,249,140,0,20.22,0.0,0.5,4.84,0.0,1.0,29.06,NaN,NaN
2913951,2,2023-02-28 23:26:02,2023-02-28 23:37:10,NaN,2.47,NaN,None,186,79,0,13.66,0.0,0.5,2.65,0.0,1.0,20.31,NaN,NaN
2913952,2,2023-02-28 23:24:00,2023-02-28 23:38:00,NaN,3.49,NaN,None,158,143,0,17.64,0.0,0.5,0.00,0.0,1.0,21.64,NaN,NaN
2913953,2,2023-02-28 23:03:00,2023-02-28 23:10:00,NaN,2.13,NaN,None,79,162,0,13.56,0.0,0.5,2.63,0.0,1.0,20.19,NaN,NaN
2913954,2,2023-02-28 23:03:03,2023-02-28 23:12:51,NaN,2.28,NaN,None,161,140,0,14.89,0.0,0.5,3.78,0.0,1.0,22.67,NaN,NaN

In [ ]:
# Imprime los resultados
print("Viajes enero :")
print()
print("Nulos por columna:", nulos_feb)
print()
print("Duplicados:", duplicados_feb)
print()
print("Outliers:", outliers_feb)
print()

Viajes enero :

Nulos por columna: VendorID                     0
tpep_pickup_datetime         0
tpep_dropoff_datetime        0
passenger_count          76817
trip_distance                0
RatecodeID               76817
store_and_fwd_flag       76817
PULocationID                 0
DOLocationID                 0
payment_type                 0
fare_amount                  0
extra                        0
mta_tax                      0
tip_amount                   0
tolls_amount                 0
improvement_surcharge        0
total_amount                 0
congestion_surcharge     76817
Airport_fee              76817
dtype: int64

Duplicados: 0

Outliers: VendorID                   1201
passenger_count          674446
trip_distance            362406
RatecodeID               138454
PULocationID                  0
DOLocationID                  0
payment_type             604366
fare_amount              307750
extra                     43505
mta_tax                   47086
tip_amount               203739
tolls_amount             210803
improvement_surcharge     30890
total_amount             343988
congestion_surcharge     223609
Airport_fee              225463
dtype: int64

In [ ]:
enero.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3066766 entries, 0 to 3066765
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int64(4), object(1)
memory usage: 444.6+ MB

Los conjuntos de datos para los meses de enero a septiembre tienen columnas similares y se han cargado correctamente con sus tipos de datos correspondientes. Aquí hay un resumen de la información:

VendorID: Identificación del proveedor del servicio de taxi.

tpep_pickup_datetime: Marca de tiempo que indica la fecha y hora de recogida del pasajero.

tpep_dropoff_datetime: Marca de tiempo que indica la fecha y hora de dejada del pasajero.

passenger_count: Número de pasajeros en el viaje.

trip_distance: Distancia total del viaje en millas.

RatecodeID: Código que indica el tipo de tarifa cobrada.

store_and_fwd_flag: Indica si el registro fue almacenado y reenviado (almacenado temporalmente cuando el vehículo no tenía conexión).

PULocationID: Identificación del lugar de recogida.

DOLocationID: Identificación del lugar de dejada.

payment_type: Método de pago utilizado (efectivo, tarjeta, etc.).

fare_amount: Tarifa del viaje sin propina.

extra: Cargo adicional por situaciones como viajes nocturnos o picos de demanda.

mta_tax: Tarifa impuesta por la Autoridad de Tránsito Metropolitano.

tip_amount: Cantidad de propina.

tolls_amount: Peajes pagados durante el viaje.

improvement_surcharge: Tarifa de mejora.

total_amount: Monto total pagado por el pasajero.

congestion_surcharge: Cargo por congestión.

Airport_fee: Tarifa de aeropuerto.

In [ ]:
enero.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00

In [ ]:
febrero.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2913955 entries, 0 to 2913954
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 389.1+ MB

In [ ]:
febrero.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,1,2023-02-01 00:32:53,2023-02-01 00:34:34,2.0,0.30,1.0,N,142,163,2,4.4,3.50,0.5,0.0,0.0,1.0,9.40,2.5,0.00
1,2,2023-02-01 00:35:16,2023-02-01 00:35:30,1.0,0.00,1.0,N,71,71,4,-3.0,-1.00,-0.5,0.0,0.0,-1.0,-5.50,0.0,0.00
2,2,2023-02-01 00:35:16,2023-02-01 00:35:30,1.0,0.00,1.0,N,71,71,4,3.0,1.00,0.5,0.0,0.0,1.0,5.50,0.0,0.00
3,1,2023-02-01 00:29:33,2023-02-01 01:01:38,0.0,18.80,1.0,N,132,26,1,70.9,2.25,0.5,0.0,0.0,1.0,74.65,0.0,1.25
4,2,2023-02-01 00:12:28,2023-02-01 00:25:46,1.0,3.22,1.0,N,161,145,1,17.0,1.00,0.5,3.3,0.0,1.0,25.30,2.5,0.00

In [ ]:
marzo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3403766 entries, 0 to 3403765
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 454.5+ MB

In [ ]:
marzo.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2023-03-01 00:06:43,2023-03-01 00:16:43,1.0,0.00,1.0,N,238,42,2,8.6,1.0,0.5,0.00,0.0,1.0,11.10,0.0,0.00
1,2,2023-03-01 00:08:25,2023-03-01 00:39:30,2.0,12.40,1.0,N,138,231,1,52.7,6.0,0.5,12.54,0.0,1.0,76.49,2.5,1.25
2,1,2023-03-01 00:15:04,2023-03-01 00:29:26,0.0,3.30,1.0,N,140,186,1,18.4,3.5,0.5,4.65,0.0,1.0,28.05,2.5,0.00
3,1,2023-03-01 00:49:37,2023-03-01 01:01:05,1.0,2.90,1.0,N,140,43,1,15.6,3.5,0.5,4.10,0.0,1.0,24.70,2.5,0.00
4,2,2023-03-01 00:08:04,2023-03-01 00:11:06,1.0,1.23,1.0,N,79,137,1,7.2,1.0,0.5,2.44,0.0,1.0,14.64,2.5,0.00

In [ ]:
abril.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3288250 entries, 0 to 3288249
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 439.0+ MB

In [ ]:
abril.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,1,2023-04-01 00:14:49,2023-04-01 00:45:01,2.0,4.90,1.0,N,48,223,1,28.9,3.5,0.5,6.0,0.00,1.0,39.9,2.5,0.00
1,2,2023-04-01 00:00:24,2023-04-01 00:56:19,1.0,21.89,2.0,N,132,43,2,70.0,0.0,0.5,0.0,6.55,1.0,81.8,2.5,1.25
2,1,2023-04-01 00:03:50,2023-04-01 00:14:42,2.0,1.30,1.0,N,148,113,1,11.4,3.5,0.5,2.0,0.00,1.0,18.4,2.5,0.00
3,1,2023-04-01 00:53:18,2023-04-01 01:01:28,1.0,1.50,1.0,N,249,79,1,10.0,3.5,0.5,1.0,0.00,1.0,16.0,2.5,0.00
4,2,2023-04-01 00:07:00,2023-04-01 00:17:16,2.0,1.49,1.0,N,158,246,1,11.4,1.0,0.5,1.0,0.00,1.0,17.4,2.5,0.00

In [ ]:
mayo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3513649 entries, 0 to 3513648
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 469.1+ MB

In [ ]:
mayo.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,1,2023-05-01 00:33:13,2023-05-01 00:53:01,0.0,7.80,1.0,N,138,43,1,33.8,7.75,0.5,8.60,0.00,1.0,51.65,0.0,1.75
1,1,2023-05-01 00:42:49,2023-05-01 01:11:18,2.0,8.10,1.0,N,138,262,1,35.9,10.25,0.5,9.50,0.00,1.0,57.15,2.5,1.75
2,1,2023-05-01 00:56:34,2023-05-01 01:13:39,2.0,9.10,1.0,N,138,141,1,35.2,10.25,0.5,10.70,6.55,1.0,64.20,2.5,1.75
3,2,2023-05-01 00:00:52,2023-05-01 00:20:12,1.0,8.21,1.0,N,138,140,1,33.1,6.00,0.5,2.24,0.00,1.0,47.09,2.5,1.75
4,1,2023-05-01 00:05:50,2023-05-01 00:19:41,0.0,7.90,1.0,N,138,263,1,31.0,10.25,0.5,9.85,6.55,1.0,59.15,2.5,1.75

In [ ]:
junio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3307234 entries, 0 to 3307233
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 441.6+ MB

In [ ]:
junio.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,1,2023-06-01 00:08:48,2023-06-01 00:29:41,1.0,3.40,1.0,N,140,238,1,21.9,3.50,0.5,6.70,0.0,1.0,33.60,2.5,0.00
1,1,2023-06-01 00:15:04,2023-06-01 00:25:18,0.0,3.40,1.0,N,50,151,1,15.6,3.50,0.5,3.00,0.0,1.0,23.60,2.5,0.00
2,1,2023-06-01 00:48:24,2023-06-01 01:07:07,1.0,10.20,1.0,N,138,97,1,40.8,7.75,0.5,10.00,0.0,1.0,60.05,0.0,1.75
3,2,2023-06-01 00:54:03,2023-06-01 01:17:29,3.0,9.83,1.0,N,100,244,1,39.4,1.00,0.5,8.88,0.0,1.0,53.28,2.5,0.00
4,2,2023-06-01 00:18:44,2023-06-01 00:27:18,1.0,1.17,1.0,N,137,234,1,9.3,1.00,0.5,0.72,0.0,1.0,15.02,2.5,0.00

In [ ]:
julio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2907108 entries, 0 to 2907107
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 388.1+ MB

In [ ]:
julio.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,1,2023-07-01 00:29:59,2023-07-01 00:40:15,1.0,1.80,1.0,N,140,263,1,12.1,3.5,0.5,5.10,0.0,1.0,22.20,2.5,0.0
1,2,2023-07-01 00:03:25,2023-07-01 00:23:44,1.0,2.31,1.0,N,163,163,2,19.1,1.0,0.5,0.00,0.0,1.0,24.10,2.5,0.0
2,2,2023-07-01 00:38:29,2023-07-01 00:48:53,1.0,2.36,1.0,N,142,262,1,13.5,1.0,0.5,3.70,0.0,1.0,22.20,2.5,0.0
3,2,2023-07-01 00:14:16,2023-07-01 00:29:13,1.0,4.36,1.0,N,68,24,1,19.8,1.0,0.5,4.96,0.0,1.0,29.76,2.5,0.0
4,1,2023-07-01 00:11:15,2023-07-01 00:20:47,0.0,1.60,1.0,N,161,107,1,11.4,3.5,0.5,3.25,0.0,1.0,19.65,2.5,0.0

In [ ]:
agosto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2824209 entries, 0 to 2824208
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 377.1+ MB

In [ ]:
agosto.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,1,2023-08-01 00:26:44,2023-08-01 00:45:25,1.0,4.30,1.0,N,263,90,1,21.9,3.50,0.5,5.35,0.00,1.0,32.25,2.5,0.00
1,1,2023-08-01 00:55:42,2023-08-01 01:00:53,1.0,0.00,1.0,N,132,132,3,5.1,2.75,0.5,0.00,0.00,1.0,9.35,0.0,1.75
2,2,2023-08-01 00:32:04,2023-08-01 01:09:03,1.0,20.61,2.0,N,132,13,1,70.0,0.00,0.5,14.80,0.00,1.0,90.55,2.5,1.75
3,2,2023-08-01 00:13:37,2023-08-01 00:41:15,1.0,13.37,1.0,N,138,254,2,54.1,6.00,0.5,0.00,6.55,1.0,69.90,0.0,1.75
4,1,2023-08-01 00:24:46,2023-08-01 00:41:31,2.0,3.20,5.0,N,140,143,4,20.0,0.00,0.0,0.00,0.00,1.0,21.00,0.0,0.00

In [ ]:
septiembre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2846722 entries, 0 to 2846721
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 380.1+ MB

In [ ]:
septiembre.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,1,2023-09-01 00:15:37,2023-09-01 00:20:21,1.0,0.80,1.0,N,163,230,2,6.5,3.5,0.5,0.00,0.0,1.0,11.50,2.5,0.00
1,2,2023-09-01 00:18:40,2023-09-01 00:30:28,2.0,2.34,1.0,N,236,233,1,14.2,1.0,0.5,2.00,0.0,1.0,21.20,2.5,0.00
2,2,2023-09-01 00:35:01,2023-09-01 00:39:04,1.0,1.62,1.0,N,162,236,1,8.6,1.0,0.5,2.00,0.0,1.0,15.60,2.5,0.00
3,2,2023-09-01 00:45:45,2023-09-01 00:47:37,1.0,0.74,1.0,N,141,229,1,5.1,1.0,0.5,1.00,0.0,1.0,11.10,2.5,0.00
4,2,2023-09-01 00:01:23,2023-09-01 00:38:05,1.0,9.85,1.0,N,138,230,1,45.0,6.0,0.5,17.02,0.0,1.0,73.77,2.5,1.75

In [ ]:
alt_fuel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 882 entries, 0 to 881
Data columns (total 22 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Category                            882 non-null    object
 1   Model                               882 non-null    object
 2   Model Year                          594 non-null    float64
 3   Manufacturer                        882 non-null    object
 4   Fuel                                882 non-null    object
 5   All-Electric Range                  222 non-null    float64
 6   PHEV Total Range                    43 non-null     float64
 7   Alternative Fuel Economy City       169 non-null    float64
 8   Alternative Fuel Economy Highway    169 non-null    float64
 9   Alternative Fuel Economy Combined   262 non-null    float64
 10  Conventional Fuel Economy City      444 non-null    float64
 11  Conventional Fuel Economy Highway   444 non-null    float64
 12  Conventional Fuel Economy Combined  444 non-null    float64
 13  Transmission Type                   640 non-null    object
 14  Transmission Make                   125 non-null    object
 15  Engine Type                         589 non-null    object
 16  Engine Size                         589 non-null    object
 17  Engine Cylinder Count               449 non-null    float64
 18  Number of Passengers                121 non-null    object
 19  Heavy-Duty Power System             245 non-null    object
 20  Notes                               179 non-null    object
 21  Drivetrain                          329 non-null    object
dtypes: float64(10), object(12)
memory usage: 151.7+ KB

In [ ]:
ruta = '/content/drive/MyDrive/Datasets/'

alt_fuel_ruta = ruta + 'Alternative Fuel Vehicles US.csv'
alt_fuel = pd.read_csv(alt_fuel_ruta)

elec_alt_fuel_ruta = ruta + 'Electric and Alternative Fuel Charging Stations.csv'
elec_alt_fuel = pd.read_csv(elec_alt_fuel_ruta)

elec_car_ruta = ruta + 'ElectricCarData_Clean.csv'
elec_car_clean = pd.read_csv(elec_car_ruta)

elec_car_ruta_norm = ruta + 'ElectricCarData_Norm.csv'
elec_car_norm = pd.read_csv(elec_car_ruta_norm)

light_duty_ruta = ruta + 'Light Duty Vehicles.csv'
light_duty = pd.read_csv(light_duty_ruta)

vihicle_fuel_ruta = ruta + 'Light Duty Vehicles.csv'
vihicle_fuel = pd.read_csv(vihicle_fuel_ruta)

taxi_zones_ruta = ruta + 'taxi+_zone_lookup.csv'
taxi_zones_lookup = pd.read_csv(taxi_zones_ruta)

In [ ]:
alt_fuel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 882 entries, 0 to 881
Data columns (total 22 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Category                            882 non-null    object
 1   Model                               882 non-null    object
 2   Model Year                          594 non-null    float64
 3   Manufacturer                        882 non-null    object
 4   Fuel                                882 non-null    object
 5   All-Electric Range                  222 non-null    float64
 6   PHEV Total Range                    43 non-null     float64
 7   Alternative Fuel Economy City       169 non-null    float64
 8   Alternative Fuel Economy Highway    169 non-null    float64
 9   Alternative Fuel Economy Combined   262 non-null    float64
 10  Conventional Fuel Economy City      444 non-null    float64
 11  Conventional Fuel Economy Highway   444 non-null    float64
 12  Conventional Fuel Economy Combined  444 non-null    float64
 13  Transmission Type                   640 non-null    object
 14  Transmission Make                   125 non-null    object
 15  Engine Type                         589 non-null    object
 16  Engine Size                         589 non-null    object
 17  Engine Cylinder Count               449 non-null    float64
 18  Number of Passengers                121 non-null    object
 19  Heavy-Duty Power System             245 non-null    object
 20  Notes                               179 non-null    object
 21  Drivetrain                          329 non-null    object
dtypes: float64(10), object(12)
memory usage: 151.7+ KB

In [ ]:
alt_fuel.head()

,Category,Model,Model Year,Manufacturer,Fuel,All-Electric Range,PHEV Total Range,Alternative Fuel Economy City,Alternative Fuel Economy Highway,Alternative Fuel Economy Combined,Conventional Fuel Economy City,Conventional Fuel Economy Highway,Conventional Fuel Economy Combined,Transmission Type,Transmission Make,Engine Type,Engine Size,Engine Cylinder Count,Number of Passengers,Heavy-Duty Power System,Notes,Drivetrain
0,Sedan/Wagon,NSX,2022.0,Acura,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,21.0,22.0,21.0,Auto,NaN,SI,3.5L,6.0,NaN,NaN,NaN,AWD
1,Sedan/Wagon,A3,2022.0,Audi,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,29.0,38.0,32.0,Auto,NaN,SI,2.0L,4.0,NaN,NaN,NaN,FWD
2,Sedan/Wagon,A3 quattro,2022.0,Audi,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,28.0,36.0,31.0,Auto,NaN,SI,2.0L,4.0,NaN,NaN,NaN,AWD
3,Sedan/Wagon,A4 allroad quattro,2022.0,Audi,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,24.0,30.0,26.0,Auto,NaN,SI,2.0L,4.0,NaN,NaN,NaN,AWD
4,Sedan/Wagon,A4 quattro,2022.0,Audi,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,26.0,34.0,29.0,Auto,NaN,SI,2.0L,4.0,NaN,NaN,NaN,AWD

In [ ]:
elec_alt_fuel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70406 entries, 0 to 70405
Data columns (total 65 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Fuel Type Code                    70406 non-null  object
 1   Station Name                      70406 non-null  object
 2   Street Address                    70405 non-null  object
 3   Intersection Directions           4493 non-null   object
 4   City                              70406 non-null  object
 5   State                             70406 non-null  object
 6   ZIP                               70405 non-null  object
 7   Plus4                             0 non-null      float64
 8   Station Phone                     65204 non-null  object
 9   Status Code                       70406 non-null  object
 10  Expected Date                     1218 non-null   object
 11  Groups With Access Code           70406 non-null  object
 12  Access Days Time                  66628 non-null  object
 13  Cards Accepted                    11289 non-null  object
 14  BD Blends                         1217 non-null   object
 15  NG Fill Type Code                 1603 non-null   object
 16  NG PSI                            1597 non-null   object
 17  EV Level1 EVSE Num                286 non-null    float64
 18  EV Level2 EVSE Num                54144 non-null  float64
 19  EV DC Fast Count                  8307 non-null   float64
 20  EV Other Info                     49 non-null     object
 21  EV Network                        60907 non-null  object
 22  EV Network Web                    50305 non-null  object
 23  Geocode Status                    70391 non-null  object
 24  Latitude                          70406 non-null  float64
 25  Longitude                         70406 non-null  float64
 26  Date Last Confirmed               70188 non-null  object
 27  ID                                70406 non-null  int64
 28  Updated At                        70406 non-null  object
 29  Owner Type Code                   30190 non-null  object
 30  Federal Agency ID                 955 non-null    float64
 31  Federal Agency Name               955 non-null    object
 32  Open Date                         69310 non-null  object
 33  Hydrogen Status Link              83 non-null     object
 34  NG Vehicle Class                  1780 non-null   object
 35  LPG Primary                       1867 non-null   object
 36  E85 Blender Pump                  4508 non-null   object
 37  EV Connector Types                60690 non-null  object
 38  Country                           70406 non-null  object
 39  Intersection Directions (French)  188 non-null    object
 40  Access Days Time (French)         6591 non-null   object
 41  BD Blends (French)                2 non-null      object
 42  Groups With Access Code (French)  70406 non-null  object
 43  Hydrogen Is Retail                117 non-null    object
 44  Access Code                       70406 non-null  object
 45  Access Detail Code                7423 non-null   object
 46  Federal Agency Code               955 non-null    object
 47  Facility Type                     27665 non-null  object
 48  CNG Dispenser Num                 1039 non-null   float64
 49  CNG On-Site Renewable Source      716 non-null    object
 50  CNG Total Compression Capacity    708 non-null    float64
 51  CNG Storage Capacity              357 non-null    float64
 52  LNG On-Site Renewable Source      62 non-null     object
 53  E85 Other Ethanol Blends          1458 non-null   object
 54  EV Pricing                        16961 non-null  object
 55  EV Pricing (French)               2032 non-null   object
 56  LPG Nozzle Types                  1826 non-null   object
 57  Hydrogen Pressures                116 non-null    object
 58  Hydrogen Standards                116 non-null    object
 59  CNG Fill Type Code                1603 non-null   object
 60  CNG PSI                           1597 non-null   object
 61  CNG Vehicle Class                 1622 non-null   object
 62  LNG Vehicle Class                 158 non-null    object
 63  EV On-Site Renewable Source       370 non-null    object
 64  Restricted Access                 53435 non-null  object
dtypes: float64(10), int64(1), object(54)
memory usage: 34.9+ MB

In [ ]:
elec_alt_fuel.head()

,Fuel Type Code,Station Name,Street Address,Intersection Directions,City,State,ZIP,Plus4,Station Phone,Status Code,Expected Date,Groups With Access Code,Access Days Time,Cards Accepted,BD Blends,NG Fill Type Code,NG PSI,EV Level1 EVSE Num,EV Level2 EVSE Num,EV DC Fast Count,EV Other Info,EV Network,EV Network Web,Geocode Status,Latitude,Longitude,Date Last Confirmed,ID,Updated At,Owner Type Code,Federal Agency ID,Federal Agency Name,Open Date,Hydrogen Status Link,NG Vehicle Class,LPG Primary,E85 Blender Pump,EV Connector Types,Country,Intersection Directions (French),Access Days Time (French),BD Blends (French),Groups With Access Code (French),Hydrogen Is Retail,Access Code,Access Detail Code,Federal Agency Code,Facility Type,CNG Dispenser Num,CNG On-Site Renewable Source,CNG Total Compression Capacity,CNG Storage Capacity,LNG On-Site Renewable Source,E85 Other Ethanol Blends,EV Pricing,EV Pricing (French),LPG Nozzle Types,Hydrogen Pressures,Hydrogen Standards,CNG Fill Type Code,CNG PSI,CNG Vehicle Class,LNG Vehicle Class,EV On-Site Renewable Source,Restricted Access
0,CNG,Spire - Montgomery Operations Center,2951 Chestnut St,NaN,Montgomery,AL,36107,NaN,NaN,E,NaN,Private,NaN,NaN,NaN,B,3600,NaN,NaN,NaN,NaN,NaN,NaN,200-9,32.367916,-86.267021,2022-06-14,17,2022-06-14 16:22:47 UTC,T,NaN,NaN,2010-12-01,NaN,MD,NaN,NaN,NaN,US,NaN,NaN,NaN,Privé,NaN,private,NaN,NaN,STANDALONE_STATION,NaN,NONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,3600,MD,NaN,NaN,NaN
1,CNG,PS Energy - Atlanta,340 Whitehall St,"From I-7585 N, exit 91 to Central Ave, left on...",Atlanta,GA,30303,NaN,770-350-3000,E,NaN,Public - Card key at all times,24 hours daily,Comdata FleetOne FuelMan Voyager Wright_Exp,NaN,Q,3600,NaN,NaN,NaN,NaN,NaN,NaN,200-8,33.745843,-84.398837,2021-08-04,42,2022-02-10 19:42:29 UTC,P,NaN,NaN,1994-07-15,NaN,MD,NaN,NaN,NaN,US,NaN,NaN,NaN,Public - Carte-clé en tout temps,NaN,public,KEY_ALWAYS,NaN,STANDALONE_STATION,1.0,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q,3600,MD,NaN,NaN,False
2,CNG,Metropolitan Atlanta Rapid Transit Authority,2424 Piedmont Rd NE,NaN,Atlanta,GA,30324,NaN,NaN,E,NaN,Private - Government only,NaN,NaN,NaN,Q,3000,NaN,NaN,NaN,NaN,NaN,NaN,200-8,33.821911,-84.367461,2021-08-04,45,2022-02-10 19:42:29 UTC,LG,NaN,NaN,1996-12-15,NaN,LD,NaN,NaN,NaN,US,NaN,NaN,NaN,Privé - Réservé au gouvernement,NaN,private,GOVERNMENT,NaN,FLEET_GARAGE,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q,3000,LD,NaN,NaN,NaN
3,CNG,United Parcel Service,270 Marvin Miller Dr,NaN,Atlanta,GA,30336,NaN,NaN,E,NaN,Private,NaN,NaN,NaN,B,3600,NaN,NaN,NaN,NaN,NaN,NaN,200-9,33.760256,-84.543822,2022-06-14,64,2022-06-14 16:22:47 UTC,P,NaN,NaN,1997-01-01,NaN,HD,NaN,NaN,NaN,US,NaN,NaN,NaN,Privé,NaN,private,NaN,NaN,STANDALONE_STATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,3600,HD,NaN,NaN,NaN
4,CNG,Arkansas Oklahoma Gas Corp,2100 S Waldron Rd,NaN,Fort Smith,AR,72903,NaN,479-783-3188,E,NaN,Public - Credit card at all times,24 hours daily,FuelMan M V Wright_Exp,NaN,Q,3600,NaN,NaN,NaN,NaN,NaN,NaN,200-9,35.362213,-94.375338,2022-06-14,73,2022-06-14 16:22:47 UTC,T,NaN,NaN,1997-01-01,NaN,MD,NaN,NaN,NaN,US,NaN,NaN,NaN,Public - Carte de crédit en tout temps,NaN,public,CREDIT_CARD_ALWAYS,NaN,UTILITY,1.0,NONE,250.0,57855.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q,3600,MD,NaN,NaN,False

In [ ]:
elec_car_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Brand            103 non-null    object
 1   Model            103 non-null    object
 2   AccelSec         103 non-null    float64
 3   TopSpeed_KmH     103 non-null    int64
 4   Range_Km         103 non-null    int64
 5   Efficiency_WhKm  103 non-null    int64
 6   FastCharge_KmH   103 non-null    object
 7   RapidCharge      103 non-null    object
 8   PowerTrain       103 non-null    object
 9   PlugType         103 non-null    object
 10  BodyStyle        103 non-null    object
 11  Segment          103 non-null    object
 12  Seats            103 non-null    int64
 13  PriceEuro        103 non-null    int64
dtypes: float64(1), int64(5), object(8)
memory usage: 11.4+ KB

In [ ]:
elec_car_clean.head()

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,Tesla,Model 3 Long Range Dual Motor,4.6,233,450,161,940,Yes,AWD,Type 2 CCS,Sedan,D,5,55480
1,Volkswagen,ID.3 Pure,10.0,160,270,167,250,Yes,RWD,Type 2 CCS,Hatchback,C,5,30000
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440
3,BMW,iX3,6.8,180,360,206,560,Yes,RWD,Type 2 CCS,SUV,D,5,68040
4,Honda,e,9.5,145,170,168,190,Yes,RWD,Type 2 CCS,Hatchback,B,4,32997

In [ ]:
elec_car_norm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Brand        103 non-null    object
 1   Model        103 non-null    object
 2   Accel        103 non-null    object
 3   TopSpeed     103 non-null    object
 4   Range        103 non-null    object
 5   Efficiency   103 non-null    object
 6   FastCharge   103 non-null    object
 7   RapidCharge  103 non-null    object
 8   PowerTrain   103 non-null    object
 9   PlugType     103 non-null    object
 10  BodyStyle    103 non-null    object
 11  Segment      103 non-null    object
 12  Seats        103 non-null    int64
 13  PriceEuro    103 non-null    int64
dtypes: int64(2), object(12)
memory usage: 11.4+ KB

In [ ]:
elec_car_norm.head()

,Brand,Model,Accel,TopSpeed,Range,Efficiency,FastCharge,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,Tesla,Model 3 Long Range Dual Motor,4.6 sec,233 km/h,450 km,161 Wh/km,940 km/h,Rapid charging possible,All Wheel Drive,Type 2 CCS,Sedan,D,5,55480
1,Volkswagen,ID.3 Pure,10.0 sec,160 km/h,270 km,167 Wh/km,250 km/h,Rapid charging possible,Rear Wheel Drive,Type 2 CCS,Hatchback,C,5,30000
2,Polestar,2,4.7 sec,210 km/h,400 km,181 Wh/km,620 km/h,Rapid charging possible,All Wheel Drive,Type 2 CCS,Liftback,D,5,56440
3,BMW,iX3,6.8 sec,180 km/h,360 km,206 Wh/km,560 km/h,Rapid charging possible,Rear Wheel Drive,Type 2 CCS,SUV,D,5,68040
4,Honda,e,9.5 sec,145 km/h,170 km,168 Wh/km,190 km/h,Rapid charging possible,Rear Wheel Drive,Type 2 CCS,Hatchback,B,4,32997

In [ ]:
light_duty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3008 entries, 0 to 3007
Data columns (total 29 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Vehicle ID                          3008 non-null   int64
 1   Fuel ID                             3008 non-null   int64
 2   Fuel Configuration ID               2973 non-null   float64
 3   Manufacturer ID                     3008 non-null   int64
 4   Category ID                         3008 non-null   int64
 5   Model                               3008 non-null   object
 6   Model Year                          3008 non-null   int64
 7   Alternative Fuel Economy City       1595 non-null   float64
 8   Alternative Fuel Economy Highway    1505 non-null   float64
 9   Alternative Fuel Economy Combined   467 non-null    float64
 10  Conventional Fuel Economy City      2044 non-null   float64
 11  Conventional Fuel Economy Highway   2046 non-null   float64
 12  Conventional Fuel Economy Combined  763 non-null    float64
 13  Transmission Type                   2924 non-null   object
 14  Engine Type                         2211 non-null   object
 15  Engine Size                         2874 non-null   object
 16  Engine Cylinder Count               2443 non-null   float64
 17  Engine Description                  1971 non-null   object
 18  Manufacturer                        3008 non-null   object
 19  Manufacturer URL                    2844 non-null   object
 20  Category                            3008 non-null   object
 21  Fuel Code                           3008 non-null   object
 22  Fuel                                3008 non-null   object
 23  Fuel Configuration Name             2973 non-null   object
 24  Electric-Only Range                 374 non-null    float64
 25  PHEV Total Range                    43 non-null     float64
 26  PHEV Type                           176 non-null    object
 27  Notes                               73 non-null     object
 28  Drivetrain                          329 non-null    object
dtypes: float64(10), int64(5), object(14)
memory usage: 681.6+ KB

In [ ]:
light_duty.head()

,Vehicle ID,Fuel ID,Fuel Configuration ID,Manufacturer ID,Category ID,Model,Model Year,Alternative Fuel Economy City,Alternative Fuel Economy Highway,Alternative Fuel Economy Combined,Conventional Fuel Economy City,Conventional Fuel Economy Highway,Conventional Fuel Economy Combined,Transmission Type,Engine Type,Engine Size,Engine Cylinder Count,Engine Description,Manufacturer,Manufacturer URL,Category,Fuel Code,Fuel,Fuel Configuration Name,Electric-Only Range,PHEV Total Range,PHEV Type,Notes,Drivetrain
0,13044,45,9.0,365,27,NSX,2022,NaN,NaN,NaN,21.0,22.0,21.0,Auto,SI,3.5L,6.0,3.5L V6,Acura,http://www.acura.com/,Sedan/Wagon,HYBR,Hybrid Electric,Hybrid Electric,NaN,NaN,NaN,NaN,AWD
1,12854,45,9.0,377,27,A3,2022,NaN,NaN,NaN,29.0,38.0,32.0,Auto,SI,2.0L,4.0,2.0L I4,Audi,http://progress.audiusa.com/,Sedan/Wagon,HYBR,Hybrid Electric,Hybrid Electric,NaN,NaN,NaN,NaN,FWD
2,12842,45,9.0,377,27,A3 quattro,2022,NaN,NaN,NaN,28.0,36.0,31.0,Auto,SI,2.0L,4.0,2.0L I4,Audi,http://progress.audiusa.com/,Sedan/Wagon,HYBR,Hybrid Electric,Hybrid Electric,NaN,NaN,NaN,NaN,AWD
3,12783,45,9.0,377,27,A4 allroad quattro,2022,NaN,NaN,NaN,24.0,30.0,26.0,Auto,SI,2.0L,4.0,2.0L I4,Audi,http://progress.audiusa.com/,Sedan/Wagon,HYBR,Hybrid Electric,Hybrid Electric,NaN,NaN,NaN,NaN,AWD
4,12782,45,9.0,377,27,A4 quattro,2022,NaN,NaN,NaN,26.0,34.0,29.0,Auto,SI,2.0L,4.0,2.0L I4,Audi,http://progress.audiusa.com/,Sedan/Wagon,HYBR,Hybrid Electric,Hybrid Electric,NaN,NaN,NaN,NaN,AWD

In [ ]:
vihicle_fuel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3008 entries, 0 to 3007
Data columns (total 29 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Vehicle ID                          3008 non-null   int64
 1   Fuel ID                             3008 non-null   int64
 2   Fuel Configuration ID               2973 non-null   float64
 3   Manufacturer ID                     3008 non-null   int64
 4   Category ID                         3008 non-null   int64
 5   Model                               3008 non-null   object
 6   Model Year                          3008 non-null   int64
 7   Alternative Fuel Economy City       1595 non-null   float64
 8   Alternative Fuel Economy Highway    1505 non-null   float64
 9   Alternative Fuel Economy Combined   467 non-null    float64
 10  Conventional Fuel Economy City      2044 non-null   float64
 11  Conventional Fuel Economy Highway   2046 non-null   float64
 12  Conventional Fuel Economy Combined  763 non-null    float64
 13  Transmission Type                   2924 non-null   object
 14  Engine Type                         2211 non-null   object
 15  Engine Size                         2874 non-null   object
 16  Engine Cylinder Count               2443 non-null   float64
 17  Engine Description                  1971 non-null   object
 18  Manufacturer                        3008 non-null   object
 19  Manufacturer URL                    2844 non-null   object
 20  Category                            3008 non-null   object
 21  Fuel Code                           3008 non-null   object
 22  Fuel                                3008 non-null   object
 23  Fuel Configuration Name             2973 non-null   object
 24  Electric-Only Range                 374 non-null    float64
 25  PHEV Total Range                    43 non-null     float64
 26  PHEV Type                           176 non-null    object
 27  Notes                               73 non-null     object
 28  Drivetrain                          329 non-null    object
dtypes: float64(10), int64(5), object(14)
memory usage: 681.6+ KB

In [ ]:
vihicle_fuel.head()

,Vehicle ID,Fuel ID,Fuel Configuration ID,Manufacturer ID,Category ID,Model,Model Year,Alternative Fuel Economy City,Alternative Fuel Economy Highway,Alternative Fuel Economy Combined,Conventional Fuel Economy City,Conventional Fuel Economy Highway,Conventional Fuel Economy Combined,Transmission Type,Engine Type,Engine Size,Engine Cylinder Count,Engine Description,Manufacturer,Manufacturer URL,Category,Fuel Code,Fuel,Fuel Configuration Name,Electric-Only Range,PHEV Total Range,PHEV Type,Notes,Drivetrain
0,13044,45,9.0,365,27,NSX,2022,NaN,NaN,NaN,21.0,22.0,21.0,Auto,SI,3.5L,6.0,3.5L V6,Acura,http://www.acura.com/,Sedan/Wagon,HYBR,Hybrid Electric,Hybrid Electric,NaN,NaN,NaN,NaN,AWD
1,12854,45,9.0,377,27,A3,2022,NaN,NaN,NaN,29.0,38.0,32.0,Auto,SI,2.0L,4.0,2.0L I4,Audi,http://progress.audiusa.com/,Sedan/Wagon,HYBR,Hybrid Electric,Hybrid Electric,NaN,NaN,NaN,NaN,FWD
2,12842,45,9.0,377,27,A3 quattro,2022,NaN,NaN,NaN,28.0,36.0,31.0,Auto,SI,2.0L,4.0,2.0L I4,Audi,http://progress.audiusa.com/,Sedan/Wagon,HYBR,Hybrid Electric,Hybrid Electric,NaN,NaN,NaN,NaN,AWD
3,12783,45,9.0,377,27,A4 allroad quattro,2022,NaN,NaN,NaN,24.0,30.0,26.0,Auto,SI,2.0L,4.0,2.0L I4,Audi,http://progress.audiusa.com/,Sedan/Wagon,HYBR,Hybrid Electric,Hybrid Electric,NaN,NaN,NaN,NaN,AWD
4,12782,45,9.0,377,27,A4 quattro,2022,NaN,NaN,NaN,26.0,34.0,29.0,Auto,SI,2.0L,4.0,2.0L I4,Audi,http://progress.audiusa.com/,Sedan/Wagon,HYBR,Hybrid Electric,Hybrid Electric,NaN,NaN,NaN,NaN,AWD

In [ ]:
!pip install openmeteo_requests
!pip install requests_cache
!pip install retry_requests

Collecting openmeteo_requests
  Downloading openmeteo_requests-1.1.0-py3-none-any.whl (5.5 kB)
Collecting openmeteo-sdk>=1.4.0 (from openmeteo_requests)
  Downloading openmeteo_sdk-1.6.1-py3-none-any.whl (12 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from openmeteo_requests) (2.31.0)
Requirement already satisfied: flatbuffers>=23.0.0 in /usr/local/lib/python3.10/dist-packages (from openmeteo-sdk>=1.4.0->openmeteo_requests) (23.5.26)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->openmeteo_requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->openmeteo_requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->openmeteo_requests) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->openmeteo_requests) (2023.7.22)
Installing collected packages: openmeteo-sdk, openmeteo_requests
Successfully installed openmeteo-sdk-1.6.1 openmeteo_requests-1.1.0
Collecting requests_cache
  Downloading requests_cache-1.1.1-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.3/60.3 kB 2.2 MB/s eta 0:00:00
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.10/dist-packages (from requests_cache) (23.1.0)
Collecting cattrs>=22.2 (from requests_cache)
  Downloading cattrs-23.2.2-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 4.2 MB/s eta 0:00:00
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests_cache) (4.0.0)
Requirement already satisfied: requests>=2.22 in /usr/local/lib/python3.10/dist-packages (from requests_cache) (2.31.0)
Collecting url-normalize>=1.4 (from requests_cache)
  Downloading url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Requirement already satisfied: urllib3>=1.25.5 in /usr/local/lib/python3.10/dist-packages (from requests_cache) (2.0.7)
Requirement already satisfied: exceptiongroup>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from cattrs>=22.2->requests_cache) (1.1.3)
Requirement already satisfied: typing-extensions!=4.6.3,>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from cattrs>=22.2->requests_cache) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.22->requests_cache) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.22->requests_cache) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.22->requests_cache) (2023.7.22)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from url-normalize>=1.4->requests_cache) (1.16.0)
Installing collected packages: url-normalize, cattrs, requests_cache
Successfully installed cattrs-23.2.2 requests_cache-1.1.1 url-normalize-1.4.3
Collecting retry_requests
  Downloading retry_requests-2.0.0-py3-none-any.whl (15 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from retry_requests) (2.31.0)
Requirement already satisfied: urllib3>=1.26 in /usr/local/lib/python3.10/dist-packages (from retry_requests) (2.0.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->retry_requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->retry_requests) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->retry_requests) (2023.7.22)
Installing collected packages: retry_requests
Successfully installed retry_requests-2.0.0

In [ ]:
import openmeteo_requests

import requests_cache
import pandas as pd
from retry_requests import retry

# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://air-quality-api.open-meteo.com/v1/air-quality"
params = {
	"latitude": 40.7143,
	"longitude": -74.006,
	"current": ["european_aqi", "us_aqi", "pm10", "pm2_5", "carbon_monoxide", "nitrogen_dioxide", "sulphur_dioxide", "ozone", "uv_index"],
	"hourly": ["pm10", "pm2_5", "carbon_monoxide", "nitrogen_dioxide", "sulphur_dioxide", "ozone", "uv_index", "uv_index_clear_sky", "us_aqi", "us_aqi_pm2_5", "us_aqi_pm10", "us_aqi_nitrogen_dioxide", "us_aqi_carbon_monoxide", "us_aqi_ozone", "us_aqi_sulphur_dioxide"],
	"timezone": "America/New_York",
	"start_date": "2022-07-29",
	"end_date": "2023-11-23"
}
responses = openmeteo.weather_api(url, params=params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print(f"Coordinates {response.Latitude()}°E {response.Longitude()}°N")
print(f"Elevation {response.Elevation()} m asl")
print(f"Timezone {response.Timezone()} {response.TimezoneAbbreviation()}")
print(f"Timezone difference to GMT+0 {response.UtcOffsetSeconds()} s")

# Current values. The order of variables needs to be the same as requested.
current = response.Current()
current_european_aqi = current.Variables(0).Value()
current_us_aqi = current.Variables(1).Value()
current_pm10 = current.Variables(2).Value()
current_pm2_5 = current.Variables(3).Value()
current_carbon_monoxide = current.Variables(4).Value()
current_nitrogen_dioxide = current.Variables(5).Value()
current_sulphur_dioxide = current.Variables(6).Value()
current_ozone = current.Variables(7).Value()
current_uv_index = current.Variables(8).Value()

print(f"Current time {current.Time()}")
print(f"Current european_aqi {current_european_aqi}")
print(f"Current us_aqi {current_us_aqi}")
print(f"Current pm10 {current_pm10}")
print(f"Current pm2_5 {current_pm2_5}")
print(f"Current carbon_monoxide {current_carbon_monoxide}")
print(f"Current nitrogen_dioxide {current_nitrogen_dioxide}")
print(f"Current sulphur_dioxide {current_sulphur_dioxide}")
print(f"Current ozone {current_ozone}")
print(f"Current uv_index {current_uv_index}")

# Process hourly data. The order of variables needs to be the same as requested.
hourly = response.Hourly()
hourly_pm10 = hourly.Variables(0).ValuesAsNumpy()
hourly_pm2_5 = hourly.Variables(1).ValuesAsNumpy()
hourly_carbon_monoxide = hourly.Variables(2).ValuesAsNumpy()
hourly_nitrogen_dioxide = hourly.Variables(3).ValuesAsNumpy()
hourly_sulphur_dioxide = hourly.Variables(4).ValuesAsNumpy()
hourly_ozone = hourly.Variables(5).ValuesAsNumpy()
hourly_uv_index = hourly.Variables(6).ValuesAsNumpy()
hourly_uv_index_clear_sky = hourly.Variables(7).ValuesAsNumpy()
hourly_us_aqi = hourly.Variables(8).ValuesAsNumpy()
hourly_us_aqi_pm2_5 = hourly.Variables(9).ValuesAsNumpy()
hourly_us_aqi_pm10 = hourly.Variables(10).ValuesAsNumpy()
hourly_us_aqi_nitrogen_dioxide = hourly.Variables(11).ValuesAsNumpy()
hourly_us_aqi_carbon_monoxide = hourly.Variables(12).ValuesAsNumpy()
hourly_us_aqi_ozone = hourly.Variables(13).ValuesAsNumpy()
hourly_us_aqi_sulphur_dioxide = hourly.Variables(14).ValuesAsNumpy()

hourly_data = {"date": pd.date_range(
	start = pd.to_datetime(hourly.Time(), unit = "s"),
	end = pd.to_datetime(hourly.TimeEnd(), unit = "s"),
	freq = pd.Timedelta(seconds = hourly.Interval()),
	inclusive = "left"
)}
hourly_data["pm10"] = hourly_pm10
hourly_data["pm2_5"] = hourly_pm2_5
hourly_data["carbon_monoxide"] = hourly_carbon_monoxide
hourly_data["nitrogen_dioxide"] = hourly_nitrogen_dioxide
hourly_data["sulphur_dioxide"] = hourly_sulphur_dioxide
hourly_data["ozone"] = hourly_ozone
hourly_data["uv_index"] = hourly_uv_index
hourly_data["uv_index_clear_sky"] = hourly_uv_index_clear_sky
hourly_data["us_aqi"] = hourly_us_aqi
hourly_data["us_aqi_pm2_5"] = hourly_us_aqi_pm2_5
hourly_data["us_aqi_pm10"] = hourly_us_aqi_pm10
hourly_data["us_aqi_nitrogen_dioxide"] = hourly_us_aqi_nitrogen_dioxide
hourly_data["us_aqi_carbon_monoxide"] = hourly_us_aqi_carbon_monoxide
hourly_data["us_aqi_ozone"] = hourly_us_aqi_ozone
hourly_data["us_aqi_sulphur_dioxide"] = hourly_us_aqi_sulphur_dioxide

hourly_dataframe = pd.DataFrame(data = hourly_data)
print(hourly_dataframe)

Coordinates 40.80000305175781°E -74.0°N
Elevation 51.0 m asl
Timezone b'America/New_York' b'EST'
Timezone difference to GMT+0 -18000 s
Current time 1701194400
Current european_aqi 26.0
Current us_aqi 23.81944465637207
Current pm10 2.700000047683716
Current pm2_5 1.899999976158142
Current carbon_monoxide 217.0
Current nitrogen_dioxide 6.800000190734863
Current sulphur_dioxide 2.9000000953674316
Current ozone 65.0
Current uv_index 1.149999976158142

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [ ]:
air_quality_ny = hourly_dataframe

In [ ]:

# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = -1)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://archive-api.open-meteo.com/v1/archive"
params = {
	"latitude": 40.7143,
	"longitude": -74.006,
	"start_date": "2022-01-01",
	"end_date": "2023-11-22",
	"daily": ["temperature_2m_max", "temperature_2m_min", "temperature_2m_mean", "precipitation_sum", "shortwave_radiation_sum"],
	"timezone": "America/New_York"
}
responses = openmeteo.weather_api(url, params=params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print(f"Coordinates {response.Latitude()}°E {response.Longitude()}°N")
print(f"Elevation {response.Elevation()} m asl")
print(f"Timezone {response.Timezone()} {response.TimezoneAbbreviation()}")
print(f"Timezone difference to GMT+0 {response.UtcOffsetSeconds()} s")

# Process daily data. The order of variables needs to be the same as requested.
daily = response.Daily()
daily_temperature_2m_max = daily.Variables(0).ValuesAsNumpy()
daily_temperature_2m_min = daily.Variables(1).ValuesAsNumpy()
daily_temperature_2m_mean = daily.Variables(2).ValuesAsNumpy()
daily_precipitation_sum = daily.Variables(3).ValuesAsNumpy()
daily_shortwave_radiation_sum = daily.Variables(4).ValuesAsNumpy()

daily_data = {"date": pd.date_range(
	start = pd.to_datetime(daily.Time(), unit = "s"),
	end = pd.to_datetime(daily.TimeEnd(), unit = "s"),
	freq = pd.Timedelta(seconds = daily.Interval()),
	inclusive = "left"
)}
daily_data["temperature_2m_max"] = daily_temperature_2m_max
daily_data["temperature_2m_min"] = daily_temperature_2m_min
daily_data["temperature_2m_mean"] = daily_temperature_2m_mean
daily_data["precipitation_sum"] = daily_precipitation_sum
daily_data["shortwave_radiation_sum"] = daily_shortwave_radiation_sum

daily_dataframe = pd.DataFrame(data = daily_data)
#print(daily_dataframe)

Coordinates 40.738136291503906°E -74.04254150390625°N
Elevation 51.0 m asl
Timezone b'America/New_York' b'EST'
Timezone difference to GMT+0 -18000 s

In [ ]:
climate_change_ny = daily_dataframe

In [ ]:
ruta = '/content/drive/MyDrive/Datasets/Countries CO2 Emission and more/energy.csv'

In [ ]:
co2 = pd.read_csv(ruta, index_col= False)

In [ ]:
co2.drop(columns=['Unnamed: 0'], inplace = True)

In [ ]:
air_quality_ny.dropna(inplace = True)

In [ ]:
air_quality_ny.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11427 entries, 163 to 11591
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     11427 non-null  datetime64[ns]
 1   pm10                     11427 non-null  float32
 2   pm2_5                    11427 non-null  float32
 3   carbon_monoxide          11427 non-null  float32
 4   nitrogen_dioxide         11427 non-null  float32
 5   sulphur_dioxide          11427 non-null  float32
 6   ozone                    11427 non-null  float32
 7   uv_index                 11427 non-null  float32
 8   uv_index_clear_sky       11427 non-null  float32
 9   us_aqi                   11427 non-null  float32
 10  us_aqi_pm2_5             11427 non-null  float32
 11  us_aqi_pm10              11427 non-null  float32
 12  us_aqi_nitrogen_dioxide  11427 non-null  float32
 13  us_aqi_carbon_monoxide   11427 non-null  float32
 14  us_aqi_ozone             11427 non-null  float32
 15  us_aqi_sulphur_dioxide   11427 non-null  float32
dtypes: datetime64[ns](1), float32(15)
memory usage: 848.1 KB

In [ ]:
air_quality_ny.head()

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,uv_index,uv_index_clear_sky,us_aqi,us_aqi_pm2_5,us_aqi_pm10,us_aqi_nitrogen_dioxide,us_aqi_carbon_monoxide,us_aqi_ozone,us_aqi_sulphur_dioxide
163,2022-08-05 00:00:00,39.500000,27.100000,295.0,63.099998,7.95,96.0,0.0,0.0,58.891846,58.891846,21.689392,31.077618,0.679147,23.519634,4.334787
164,2022-08-05 01:00:00,46.299999,31.900000,312.0,69.699997,7.90,83.0,0.0,0.0,59.459221,59.459221,22.034088,34.328209,0.716184,22.823902,4.307525
165,2022-08-05 02:00:00,41.599998,28.600000,336.0,79.000000,7.85,64.0,0.0,0.0,60.514187,60.514187,22.655300,38.908592,0.765298,21.567717,4.280262
166,2022-08-05 03:00:00,32.700001,22.600000,350.0,85.199997,7.55,46.0,0.0,0.0,61.524826,61.524826,23.231058,41.962173,0.827295,19.615801,4.116685
167,2022-08-05 04:00:00,29.799999,20.700001,333.0,80.449997,6.95,44.0,0.0,0.0,62.242908,62.242908,23.594696,39.622734,0.891707,17.200060,3.789531

In [ ]:
climate_change_ny.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691 entries, 0 to 690
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     691 non-null    datetime64[ns]
 1   temperature_2m_max       691 non-null    float32
 2   temperature_2m_min       691 non-null    float32
 3   temperature_2m_mean      691 non-null    float32
 4   precipitation_sum        691 non-null    float32
 5   shortwave_radiation_sum  691 non-null    float32
dtypes: datetime64[ns](1), float32(5)
memory usage: 19.0 KB

In [ ]:
climate_change_ny.head()

,date,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,shortwave_radiation_sum
0,2022-01-01 05:00:00,11.5725,7.4225,9.605833,26.5,1.61
1,2022-01-02 05:00:00,13.6225,2.0225,9.101666,8.8,2.57
2,2022-01-03 05:00:00,1.6225,-4.7775,-1.579583,1.9,1.36
3,2022-01-04 05:00:00,0.6225,-6.5775,-3.119166,0.0,9.23
4,2022-01-05 05:00:00,6.9725,-2.1275,2.074583,0.3,3.19

KPIs Relacionados con la Reducción de Emisiones:
Reducción de CO2 por Viaje (en kg):

Fórmula: (Emisiones de CO2 de Vehículos Convencionales - Emisiones de CO2 de Vehículos con Energías Alternativas) / Número total de viajes
Justificación: Evalúa la disminución de emisiones de CO2 por viaje.
Porcentaje de Viajes sin Emisiones:

Fórmula: (Número de viajes en vehículos con energías alternativas / Número total de viajes) * 100
Justificación: Muestra la proporción de viajes libres de emisiones.
Comparación de Emisiones por Borough:

Fórmula: (Emisiones de CO2 por borough en vehículos convencionales - Emisiones de CO2 por borough en vehículos con energías alternativas)
Justificación: Identifica los boroughs que más se benefician en términos de reducción de emisiones.
Impacto en la Calidad del Aire:

Fórmula: Promedio de calidad del aire con vehículos convencionales - Promedio de calidad del aire con vehículos con energías alternativas
Justificación: Analiza el impacto en la calidad del aire en áreas específicas.
KPIs Relacionados con la Rentabilidad:
Costo Operativo por Kilómetro (en dólares):

Fórmula: (Costo total de operación de vehículos con energías alternativas / Total de kilómetros recorridos)
Justificación: Evalúa la eficiencia operativa en términos de costo por distancia recorrida.
Ingresos por Viaje:

Fórmula: Ingresos totales de vehículos con energías alternativas / Número total de viajes
Justificación: Examina la rentabilidad de cada viaje.
Porcentaje de Propinas Recibidas:

Fórmula: (Total de propinas recibidas por vehículos con energías alternativas / Ingresos totales) * 100
Justificación: Indica la satisfacción del cliente y su disposición a pagar más.
Comparación de Ingresos por Borough:

Fórmula: (Ingresos por borough en vehículos convencionales - Ingresos por borough en vehículos con energías alternativas)
Justificación: Identifica áreas con mayor potencial económico.
KPIs Generales:
Distancia Promedio de Viaje:

Fórmula: Distancia total recorrida / Número total de viajes
Justificación: Ayuda a comprender la distribución geográfica de los viajes.
Duración Promedio de Viaje:

Fórmula: Duración total de viajes / Número total de viajes
Justificación: Analiza la eficiencia en términos de tiempo de viaje.
Distribución de Viajes por Día de la Semana:

Fórmula: Número de viajes por día de la semana / Total de viajes
Justificación: Identifica patrones de demanda a lo largo de la semana.
Distribución de Viajes por Zona:

Fórmula: Número de viajes por zona / Total de viajes
Justificación: Ayuda a entender las preferencias de viaje en diferentes áreas.
KPIs Adicionales:
Eficiencia de Carga de Vehículos Eléctricos:

Fórmula: (Número de cargas completas / Número total de viajes) * 100
Justificación: Evalúa la eficiencia del sistema de carga.
Demanda en Condiciones Climáticas Adversas:

Fórmula: (Número de viajes durante condiciones climáticas adversas / Total de viajes) * 100
Justificación: Indica la resistencia del servicio a condiciones climáticas difíciles.
Índice de Satisfacción del Cliente:

Fórmula: (Número de calificaciones positivas / Total de calificaciones) * 100
Justificación: Mide la satisfacción general del cliente.
Rendimiento por Tipo de Pago:

Fórmula: (Ingresos por tipo de pago / Ingresos totales) * 100
Justificación: Analiza las preferencias de pago de los clientes.
KPIs de Marketing y Estrategia:
Efectividad de Campañas de Marketing:

Fórmula: (Aumento porcentual de viajes después de una campaña de marketing / Ingresos totales antes de la campaña)
Justificación: Evalúa el retorno de inversión de las campañas de marketing.
Crecimiento de Usuarios Registrados:

Fórmula: (Aumento porcentual de usuarios registrados / Total de usuarios registrados antes de la implementación)
Justificación: Mide la expansión de la base de usuarios.
Participación de Mercado:

Fórmula: (Número de viajes de la empresa / Total de viajes en la ciudad) * 100
Justificación: Indica la cuota de mercado de la empresa.
Número de Viajes Compartidos:

Fórmula: Número de viajes compartidos / Total de viajes
Justificación: Muestra la popularidad y aceptación de los viajes compartidos.
Nota: Estos KPIs deben ser adaptados según la disponibilidad y calidad de los datos. Además, se pueden ajustar para reflejar mejor los objetivos específicos de la empresa. La implementación en código dependerá de la plataforma y herramientas utilizadas para el análisis de datos (por ejemplo, Python con pandas y matplotlib/seaborn para visualización).

In [ ]:
import pandas as pd


# 1. Calcular la propina promedio por viaje para cada mes
propina_promedio_agosto = agosto['tip_amount'].mean()
propina_promedio_septiembre = septiembre['tip_amount'].mean()

# 2. Calcular el aumento porcentual
aumento_porcentual = ((propina_promedio_septiembre - propina_promedio_agosto) / propina_promedio_agosto) * 100

# 3. Imprimir el resultado
print(f"El aumento porcentual de la propina promedio por viaje en septiembre con respecto a agosto es del {aumento_porcentual:.2f}%.")

# Objetivo 3 % de aumento de la propina promedio:
# Motivo la propina es un dato palpable del sentimiento del cliente con respecto al servicio, ademas de proporcionar una mejora en la ganancia de los taxistas

# El aumento porcentual de la propina promedio por viaje en septiembre con respecto a agosto es del 6.29%.
# Supera el objetivo plateado

# La elección del KPI "3% de aumento de la propina promedio por viaje respecto al mes anterior (en septiembre con respecto a agosto)"
# puede estar respaldada por varias razones:

# Desempeño del Servicio: Un aumento en la propina promedio podría indicar un mayor nivel de satisfacción del
# cliente y una prestación de servicios más destacada por parte de los conductores o personal de servicio.

# Lealtad del Cliente: Un incremento en las propinas puede estar relacionado con la lealtad del cliente.
# Los clientes que están satisfechos con el servicio son más propensos a ser leales y expresar su satisfacción a través de propinas más generosas.

# Motivación del Personal: Los incentivos, como las propinas, pueden servir como motivadores para el personal.
# Si se establece un objetivo de aumento en las propinas, el personal puede estar más motivado para brindar un servicio de alta calidad.

# Indicador de Calidad del Servicio: Un aumento en las propinas generalmente se asocia con la calidad del servicio.
# Este KPI proporciona una medida cuantitativa de la percepción de los clientes sobre la calidad del servicio recibido.

# Diferenciación Competitiva: En un mercado donde la competencia es intensa, ofrecer un servicio excepcional
# puede diferenciar a una empresa de la competencia. Este KPI podría reflejar la capacidad de la empresa para destacarse en términos de calidad de servicio.

# Feedback del Cliente: Las propinas pueden considerarse como una forma directa de feedback del cliente
# sobre la experiencia general. Un aumento en las propinas podría interpretarse como un indicador positivo del nivel de satisfacción del cliente.

# Reflejo de Mejoras Operativas: Si se implementan mejoras operativas, como una mayor eficiencia en
# los tiempos de espera, rutas más eficientes, o mayor comodidad para el cliente, esto podría traducirse en un aumento en las propinas.

# Perspectiva Financiera: Aumentar las propinas contribuye directamente a los ingresos del personal de
# servicio, lo que podría tener un impacto positivo en su bienestar financiero y, en última instancia, en su desempeño laboral.

# Fidelización del Cliente: Proporcionar incentivos para propinas más altas podría fomentar la fidelización
# del cliente, ya que los clientes podrían optar por seguir utilizando los servicios de la empresa que ofrece una experiencia más gratificante.

# Medición de Resultados Tangibles: Este KPI proporciona una métrica clara y cuantificable que puede medirse
# fácilmente, permitiendo un seguimiento efectivo del desempeño en el tiempo.

El aumento porcentual de la propina promedio por viaje en septiembre con respecto a agosto es del 6.29%.

In [ ]:
# KPI disminucion del 2 % de la cantidad peajes promedio  con respesto al mes anterior , en este caso septiembre con respecto a Agosto


# 1. Calcular la cantidad promedio de peajes por viaje para cada mes
peajes_promedio_agosto = agosto['tolls_amount'].mean()
peajes_promedio_septiembre = septiembre['tolls_amount'].mean()

# 2. Calcular la disminución porcentual
disminucion_porcentual = ((peajes_promedio_agosto - peajes_promedio_septiembre) / peajes_promedio_agosto) * 100

# 3. Imprimir el resultado
print(f"La disminución porcentual de la cantidad promedio de peajes por viaje en septiembre con respecto a agosto es del {disminucion_porcentual:.2f}%.")

# La disminución porcentual de la cantidad promedio de peajes por viaje en septiembre con respecto a agosto es del 0.00%.
# No se cumplio el objetivo

# Motivos de la eleccion:

# Eficiencia Operativa: Una disminución en la cantidad promedio de peajes por
# viaje podría indicar una mayor eficiencia operativa. Menos peajes podrían estar
# relacionados con rutas más eficientes o estrategias de planificación de viajes mejoradas.

# Ahorro de Costos: Menos peajes por viaje podrían traducirse en ahorro de costos directos.
# Si se puede mantener una calidad de servicio constante o mejorarla mientras se reducen los
# costos asociados con los peajes, esto podría ser beneficioso para la rentabilidad.

# Optimización de Rutas: Una disminución en la cantidad de peajes podría reflejar la optimización
# de las rutas de viaje. Esto podría estar relacionado con el uso de tecnologías de planificación
#  de rutas más avanzadas o ajustes en las estrategias logísticas.

# Sostenibilidad Ambiental: Menos peajes podrían indicar una menor emisión de gases de efecto invernadero
# asociada con el tiempo de viaje y, por lo tanto, ser un indicador de prácticas más sostenibles desde el punto de vista ambiental.

# Indicador de Tendencia: Este KPI proporciona una medida de cambio en el tiempo. Si se mantiene constante o
# mejora, podría indicar prácticas comerciales sólidas y adaptabilidad.

# Relevancia de la Industria: Dependiendo de la industria, la cantidad de peajes puede ser una parte
# significativa de los costos operativos. Este KPI sería especialmente relevante para empresas que dependen en gran medida del transporte de mercancías.

La disminución porcentual de la cantidad promedio de peajes por viaje en septiembre con respecto a agosto es del 0.00%.

In [ ]:
import pandas as pd

# Supongamos que tienes un DataFrame llamado df
# Ajusta 'tpep_pickup_datetime' y 'tpep_dropoff_datetime' al nombre real de tus columnas

# Convierte las columnas de fecha y hora al formato adecuado
enero['tpep_pickup_datetime'] = pd.to_datetime(enero['tpep_pickup_datetime'])
enero['tpep_dropoff_datetime'] = pd.to_datetime(enero['tpep_dropoff_datetime'])

# Calcula la duración del viaje en minutos
enero['duracion'] = (enero['tpep_dropoff_datetime'] - enero['tpep_pickup_datetime']).dt.total_seconds() / 60

# Ahora, puedes proceder con el cálculo del KPI como mencioné en la respuesta anterior.

In [ ]:
import pandas as pd

# Supongamos que tienes un DataFrame llamado df
# Ajusta 'tpep_pickup_datetime' y 'tpep_dropoff_datetime' al nombre real de tus columnas

# Convierte las columnas de fecha y hora al formato adecuado
febrero['tpep_pickup_datetime'] = pd.to_datetime(febrero['tpep_pickup_datetime'])
febrero['tpep_dropoff_datetime'] = pd.to_datetime(febrero['tpep_dropoff_datetime'])

# Calcula la duración del viaje en minutos
febrero['duracion'] = (febrero['tpep_dropoff_datetime'] - febrero['tpep_pickup_datetime']).dt.total_seconds() / 60

# Ahora, puedes proceder con el cálculo del KPI como mencioné en la respuesta anterior.

In [ ]:
import pandas as pd

# Supongamos que tienes un DataFrame llamado df
# Ajusta 'tpep_pickup_datetime' y 'tpep_dropoff_datetime' al nombre real de tus columnas

# Convierte las columnas de fecha y hora al formato adecuado
marzo['tpep_pickup_datetime'] = pd.to_datetime(marzo['tpep_pickup_datetime'])
marzo['tpep_dropoff_datetime'] = pd.to_datetime(marzo['tpep_dropoff_datetime'])

# Calcula la duración del viaje en minutos
marzo['duracion'] = (marzo['tpep_dropoff_datetime'] - marzo['tpep_pickup_datetime']).dt.total_seconds() / 60

# Ahora, puedes proceder con el cálculo del KPI como mencioné en la respuesta anterior.

In [ ]:
import pandas as pd

# Supongamos que tienes un DataFrame llamado df
# Ajusta 'tpep_pickup_datetime' y 'tpep_dropoff_datetime' al nombre real de tus columnas

# Convierte las columnas de fecha y hora al formato adecuado
marzo['tpep_pickup_datetime'] = pd.to_datetime(marzo['tpep_pickup_datetime'])
marzo['tpep_dropoff_datetime'] = pd.to_datetime(marzo['tpep_dropoff_datetime'])

# Calcula la duración del viaje en minutos
marzo['duracion'] = (marzo['tpep_dropoff_datetime'] - marzo['tpep_pickup_datetime']).dt.total_seconds() / 60

# Ahora, puedes proceder con el cálculo del KPI como mencioné en la respuesta anterior.

In [ ]:
import pandas as pd

# Supongamos que tienes un DataFrame llamado df
# Ajusta 'tpep_pickup_datetime' y 'tpep_dropoff_datetime' al nombre real de tus columnas

# Convierte las columnas de fecha y hora al formato adecuado
abril['tpep_pickup_datetime'] = pd.to_datetime(abril['tpep_pickup_datetime'])
abril['tpep_dropoff_datetime'] = pd.to_datetime(abril['tpep_dropoff_datetime'])

# Calcula la duración del viaje en minutos
abril['duracion'] = (abril['tpep_dropoff_datetime'] - abril['tpep_pickup_datetime']).dt.total_seconds() / 60

# Ahora, puedes proceder con el cálculo del KPI como mencioné en la respuesta anterior.

In [ ]:
import pandas as pd

# Supongamos que tienes un DataFrame llamado df
# Ajusta 'tpep_pickup_datetime' y 'tpep_dropoff_datetime' al nombre real de tus columnas

# Convierte las columnas de fecha y hora al formato adecuado
mayo['tpep_pickup_datetime'] = pd.to_datetime(mayo['tpep_pickup_datetime'])
mayo['tpep_dropoff_datetime'] = pd.to_datetime(mayo['tpep_dropoff_datetime'])

# Calcula la duración del viaje en minutos
mayo['duracion'] = (mayo['tpep_dropoff_datetime'] - mayo['tpep_pickup_datetime']).dt.total_seconds() / 60

# Ahora, puedes proceder con el cálculo del KPI como mencioné en la respuesta anterior.

In [ ]:
import pandas as pd

# Supongamos que tienes un DataFrame llamado df
# Ajusta 'tpep_pickup_datetime' y 'tpep_dropoff_datetime' al nombre real de tus columnas

# Convierte las columnas de fecha y hora al formato adecuado
junio['tpep_pickup_datetime'] = pd.to_datetime(junio['tpep_pickup_datetime'])
junio['tpep_dropoff_datetime'] = pd.to_datetime(junio['tpep_dropoff_datetime'])

# Calcula la duración del viaje en minutos
junio['duracion'] = (junio['tpep_dropoff_datetime'] - junio['tpep_pickup_datetime']).dt.total_seconds() / 60

# Ahora, puedes proceder con el cálculo del KPI como mencioné en la respuesta anterior.

In [ ]:
import pandas as pd

# Supongamos que tienes un DataFrame llamado df
# Ajusta 'tpep_pickup_datetime' y 'tpep_dropoff_datetime' al nombre real de tus columnas

# Convierte las columnas de fecha y hora al formato adecuado
julio['tpep_pickup_datetime'] = pd.to_datetime(julio['tpep_pickup_datetime'])
julio['tpep_dropoff_datetime'] = pd.to_datetime(julio['tpep_dropoff_datetime'])

# Calcula la duración del viaje en minutos
julio['duracion'] = (abril['tpep_dropoff_datetime'] - julio['tpep_pickup_datetime']).dt.total_seconds() / 60

# Ahora, puedes proceder con el cálculo del KPI como mencioné en la respuesta anterior.

In [ ]:
import pandas as pd

# Supongamos que tienes un DataFrame llamado df
# Ajusta 'tpep_pickup_datetime' y 'tpep_dropoff_datetime' al nombre real de tus columnas

# Convierte las columnas de fecha y hora al formato adecuado
agosto['tpep_pickup_datetime'] = pd.to_datetime(agosto['tpep_pickup_datetime'])
agosto['tpep_dropoff_datetime'] = pd.to_datetime(agosto['tpep_dropoff_datetime'])

# Calcula la duración del viaje en minutos
agosto['duracion'] = (agosto['tpep_dropoff_datetime'] - agosto['tpep_pickup_datetime']).dt.total_seconds() / 60

# Ahora, puedes proceder con el cálculo del KPI como mencioné en la respuesta anterior.

In [ ]:
import pandas as pd

# Supongamos que tienes un DataFrame llamado df
# Ajusta 'tpep_pickup_datetime' y 'tpep_dropoff_datetime' al nombre real de tus columnas

# Convierte las columnas de fecha y hora al formato adecuado
septiembre['tpep_pickup_datetime'] = pd.to_datetime(septiembre['tpep_pickup_datetime'])
septiembre['tpep_dropoff_datetime'] = pd.to_datetime(septiembre['tpep_dropoff_datetime'])

# Calcula la duración del viaje en minutos
septiembre['duracion'] = (septiembre['tpep_dropoff_datetime'] - septiembre['tpep_pickup_datetime']).dt.total_seconds() / 60

# Ahora, puedes proceder con el cálculo del KPI como mencioné en la respuesta anterior.

In [ ]:
import pandas as pd



# Datos para agosto
#df_agosto = df[df['mes'] == 'agosto']  # Ajusta 'mes' al nombre real de tu columna de mes
total_amount_agosto = agosto['total_amount'].sum()
duracion_agosto = agosto['duracion'].sum()
kpi_agosto = total_amount_agosto / duracion_agosto

# Datos para septiembre
#df_septiembre = df[df['mes'] == 'septiembre']  # Ajusta 'mes' al nombre real de tu columna de mes
total_amount_septiembre = septiembre['total_amount'].sum()
duracion_septiembre = septiembre['duracion'].sum()
kpi_septiembre = total_amount_septiembre / duracion_septiembre

# Calcula el KPI objetivo (2% superior al de agosto)
kpi_objetivo = kpi_agosto * 1.02

# Compara los KPIs y verifica si se cumple el objetivo
cumple_objetivo = kpi_septiembre > kpi_objetivo

# Imprime los resultados
print(f'KPI de agosto: {kpi_agosto}')
print(f'KPI de septiembre: {kpi_septiembre}')
print(f'KPI Objetivo: {kpi_objetivo}')
print(f'Cumple el objetivo: {cumple_objetivo}')

# KPI de agosto: 1.6726230538283586
# KPI de septiembre: 1.58710914402471
# KPI Objetivo: 1.7060755149049258
# Cumple el objetivo: False

KPI de agosto: 1.6726230538283586
KPI de septiembre: 1.58710914402471
KPI Objetivo: 1.7060755149049258
Cumple el objetivo: False

In [ ]:
'''
El KPI "2% de aumento en (total_amount / duracion) del mes de septiembre con respecto al (total_amount / duracion) de agosto" podría ser relevante por varias razones:

Eficiencia del Servicio: Este KPI podría proporcionar información sobre la eficiencia del servicio de taxis durante el mes de septiembre
 en comparación con agosto. Un aumento en (total_amount / duracion) podría sugerir una mejora en la eficiencia del servicio, ya sea a
 través de rutas más eficientes, menor tráfico o una gestión más efectiva del tiempo.

Experiencia del Cliente: Si la duración del viaje es constante, un aumento en (total_amount / duracion) podría indicar que los
 clientes están dispuestos a pagar más por el servicio en septiembre, lo que podría relacionarse con una experiencia de cliente mejorada.

Optimización de Tarifas: Este KPI también podría ser útil para evaluar la efectividad de cambios en las tarifas.
Un aumento en (total_amount / duracion) podría sugerir que las tarifas ajustadas durante septiembre están siendo bien recibidas por los clientes.

Identificación de Tendencias Mensuales: Comparar este KPI a lo largo de los meses podría ayudar a identificar patrones
o tendencias estacionales en el comportamiento de los clientes y en la rentabilidad del servicio.

En resumen, este KPI podría proporcionar información valiosa sobre la eficiencia operativa, la satisfacción del cliente
 y la rentabilidad del servicio, lo que podría ser crucial para la toma de decisiones estratégicas y la optimización del rendimiento del negocio.
'''

'\nEl KPI "2% de aumento en (total_amount / duracion) del mes de septiembre con respecto al (total_amount / duracion) de agosto" podría ser relevante por varias razones:\n\nEficiencia del Servicio: Este KPI podría proporcionar información sobre la eficiencia del servicio de taxis durante el mes de septiembre\n en comparación con agosto. Un aumento en (total_amount / duracion) podría sugerir una mejora en la eficiencia del servicio, ya sea a\n través de rutas más eficientes, menor tráfico o una gestión más efectiva del tiempo.\n\nExperiencia del Cliente: Si la duración del viaje es constante, un aumento en (total_amount / duracion) podría indicar que los\n clientes están dispuestos a pagar más por el servicio en septiembre, lo que podría relacionarse con una experiencia de cliente mejorada.\n\nOptimización de Tarifas: Este KPI también podría ser útil para evaluar la efectividad de cambios en las tarifas.\nUn aumento en (total_amount / duracion) podría sugerir que las tarifas ajustadas durante septiembre están siendo bien recibidas por los clientes.\n\nIdentificación de Tendencias Mensuales: Comparar este KPI a lo largo de los meses podría ayudar a identificar patrones\no tendencias estacionales en el comportamiento de los clientes y en la rentabilidad del servicio.\n\nEn resumen, este KPI podría proporcionar información valiosa sobre la eficiencia operativa, la satisfacción del cliente\n y la rentabilidad del servicio, lo que podría ser crucial para la toma de decisiones estratégicas y la optimización del rendimiento del negocio.\n'

In [ ]:
# KPI Aumento del 2% de ganancia por distancia recorrida

# Calcular el promedio de 'total_amount' y 'trip_distance' para agosto
avg_total_amount_agosto = agosto['total_amount'].mean()
avg_trip_distance_agosto = agosto['trip_distance'].mean()

# Calcular el promedio de 'total_amount' y 'trip_distance' para septiembre
avg_total_amount_septiembre = septiembre['total_amount'].mean()
avg_trip_distance_septiembre = septiembre['trip_distance'].mean()

kpi_ag = avg_total_amount_agosto / avg_trip_distance_agosto
kpi_sep = avg_total_amount_agosto / avg_trip_distance_septiembre

print('KPI Agosto : ', kpi_ag)
print('KPI Septiembre', kpi_sep)
print('Supero el objetivo de 2% de aumento? : ', kpi_sep >= kpi_ag * 1.02)

# KPI Agosto :  5.985643728638847
# KPI Septiembre 6.6977984506843296
# Supero el objetivo de 2% de aumento? :  True

KPI Agosto :  5.985643728638847
KPI Septiembre 6.6977984506843296
Supero el objetivo de 2% de aumento? :  True

In [ ]:
'''
Motivos para hacer este KPI :

El KPI que mide el aumento del 2% de las ganancias totales promedio dividido por el promedio de la distancia total del viaje en millas puede proporcionar información valiosa sobre la eficiencia financiera en relación con la distancia recorrida. Aquí hay algunos motivos para utilizar este KPI:

Eficiencia Operativa: El KPI refleja cómo las ganancias totales han aumentado en relación con la distancia recorrida. Si este valor es positivo, indica que la empresa ha logrado aumentar sus ganancias en mayor proporción que la distancia de los viajes, lo que sugiere una mejora en la eficiencia operativa.

Rentabilidad del Viaje: Proporciona información sobre la rentabilidad promedio por milla recorrida. Un aumento en este KPI indica que la empresa está generando más ingresos por cada unidad de distancia, lo cual es beneficioso desde el punto de vista financiero.

Optimización de Rutas: Puede sugerir la eficacia en la selección de rutas o la optimización de trayectos, ya que el aumento de ganancias no está simplemente relacionado con la distancia total, sino con cómo se gestionan esos recorridos.

Tendencias a lo Largo del Tiempo: Al comparar este KPI entre diferentes periodos (por ejemplo, agosto y septiembre), se pueden identificar tendencias a lo largo del tiempo. Un aumento sostenido podría indicar prácticas comerciales efectivas.

Decisiones Estratégicas: Puede influir en la toma de decisiones estratégicas, como ajustes en tarifas, cambios en las políticas de precios o enfoques específicos para maximizar la rentabilidad de los viajes.
'''

'\nMotivos para hacer este KPI :\n\nEl KPI que mide el aumento del 2% de las ganancias totales promedio dividido por el promedio de la distancia total del viaje en millas puede proporcionar información valiosa sobre la eficiencia financiera en relación con la distancia recorrida. Aquí hay algunos motivos para utilizar este KPI:\n\nEficiencia Operativa: El KPI refleja cómo las ganancias totales han aumentado en relación con la distancia recorrida. Si este valor es positivo, indica que la empresa ha logrado aumentar sus ganancias en mayor proporción que la distancia de los viajes, lo que sugiere una mejora en la eficiencia operativa.\n\nRentabilidad del Viaje: Proporciona información sobre la rentabilidad promedio por milla recorrida. Un aumento en este KPI indica que la empresa está generando más ingresos por cada unidad de distancia, lo cual es beneficioso desde el punto de vista financiero.\n\nOptimización de Rutas: Puede sugerir la eficacia en la selección de rutas o la optimización de trayectos, ya que el aumento de ganancias no está simplemente relacionado con la distancia total, sino con cómo se gestionan esos recorridos.\n\nTendencias a lo Largo del Tiempo: Al comparar este KPI entre diferentes periodos (por ejemplo, agosto y septiembre), se pueden identificar tendencias a lo largo del tiempo. Un aumento sostenido podría indicar prácticas comerciales efectivas.\n\nDecisiones Estratégicas: Puede influir en la toma de decisiones estratégicas, como ajustes en tarifas, cambios en las políticas de precios o enfoques específicos para maximizar la rentabilidad de los viajes.\n'

In [ ]:
# KPI 1

# Calcular los ingresos totales
#ingresos_totales = taxi['total_amount'].sum()

# Calcular el numero total de pasajeros
#num_pasajeros = taxi['passenger_count'].sum()

# Calcular el ingreso promedio por pasajero
#ingreso_promedio_por_pasajero = ingresos_totales / num_pasajeros

# Establecer el objetivo del 3%
#tasa_aumento = 0.03

# Calcular el ingreso promedio proyectado por pasajero en el próximo mes
#ingreso_promedio_proyectado = ingreso_promedio_por_pasajero * (1 + tasa_aumento)

#Tiene como objetivo aumentar el ingreso por pasajero en un 3%

In [ ]:
#KPI 2

# Obtener el tiempo entre recogida y llegada al destino
#taxi['tiempo_espera'] = (taxi['tpep_dropoff_datetime'] - taxi['tpep_pickup_datetime']).dt.total_seconds() / 60  # Convertir a minutos

# Calcular el tiempo de espera promedio
#tiempo_espera_promedio = taxi['tiempo_espera'].mean()

# Establecer objetivo de reducir este tiempo en un 5%
#objetivo_tiempo_espera = tiempo_espera_promedio - (tiempo_espera_promedio * 0.05)

#Tiene como objetivo disminuir el tiempo entre recogida y llegada a destino en un 5% con el fin
#de mejorar la valoracion de los usuarios

#esa mejora en el tiempo de viaje podria hacer que los clientes no se quejen tanto del aumento del 3%
#del KPI anterior y a la vez es mejor para la empresa si los clientes estan satisfechos con la velocidad de su transporte

In [ ]:
'''

Los dataframes son estos:

enero.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3066766 entries, 0 to 3066765
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int64(4), object(1)
memory usage: 444.6+ MB

enero.head()

VendorID	tpep_pickup_datetime	tpep_dropoff_datetime	passenger_count	trip_distance	RatecodeID	store_and_fwd_flag	PULocationID	DOLocationID	payment_type	fare_amount	extra	mta_tax	tip_amount	tolls_amount	improvement_surcharge	total_amount	congestion_surcharge	airport_fee
0	2	2023-01-01 00:32:10	2023-01-01 00:40:36	1.0	0.97	1.0	N	161	141	2	9.3	1.00	0.5	0.00	0.0	1.0	14.30	2.5	0.00
1	2	2023-01-01 00:55:08	2023-01-01 01:01:27	1.0	1.10	1.0	N	43	237	1	7.9	1.00	0.5	4.00	0.0	1.0	16.90	2.5	0.00
2	2	2023-01-01 00:25:04	2023-01-01 00:37:49	1.0	2.51	1.0	N	48	238	1	14.9	1.00	0.5	15.00	0.0	1.0	34.90	2.5	0.00
3	1	2023-01-01 00:03:48	2023-01-01 00:13:25	0.0	1.90	1.0	N	138	7	1	12.1	7.25	0.5	0.00	0.0	1.0	20.85	0.0	1.25
4	2	2023-01-01 00:10:29	2023-01-01 00:21:19	1.0	1.43	1.0	N	107	79	1	11.4	1.00	0.5	3.28	0.0	1.0	19.68	2.5	0.00

febrero.info()


class 'pandas.core.frame.DataFrame'>
RangeIndex: 2913955 entries, 0 to 2913954
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 389.1+ MB

febrero.head()

VendorID	tpep_pickup_datetime	tpep_dropoff_datetime	passenger_count	trip_distance	RatecodeID	store_and_fwd_flag	PULocationID	DOLocationID	payment_type	fare_amount	extra	mta_tax	tip_amount	tolls_amount	improvement_surcharge	total_amount	congestion_surcharge	Airport_fee
0	1	2023-02-01 00:32:53	2023-02-01 00:34:34	2.0	0.30	1.0	N	142	163	2	4.4	3.50	0.5	0.0	0.0	1.0	9.40	2.5	0.00
1	2	2023-02-01 00:35:16	2023-02-01 00:35:30	1.0	0.00	1.0	N	71	71	4	-3.0	-1.00	-0.5	0.0	0.0	-1.0	-5.50	0.0	0.00
2	2	2023-02-01 00:35:16	2023-02-01 00:35:30	1.0	0.00	1.0	N	71	71	4	3.0	1.00	0.5	0.0	0.0	1.0	5.50	0.0	0.00
3	1	2023-02-01 00:29:33	2023-02-01 01:01:38	0.0	18.80	1.0	N	132	26	1	70.9	2.25	0.5	0.0	0.0	1.0	74.65	0.0	1.25
4	2	2023-02-01 00:12:28	2023-02-01 00:25:46	1.0	3.22	1.0	N	161	145	1	17.0	1.00	0.5	3.3	0.0	1.0	25.30	2.5	0.00

marzo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3403766 entries, 0 to 3403765
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 454.5+ MB

marzo.head()

VendorID	tpep_pickup_datetime	tpep_dropoff_datetime	passenger_count	trip_distance	RatecodeID	store_and_fwd_flag	PULocationID	DOLocationID	payment_type	fare_amount	extra	mta_tax	tip_amount	tolls_amount	improvement_surcharge	total_amount	congestion_surcharge	Airport_fee
0	2	2023-03-01 00:06:43	2023-03-01 00:16:43	1.0	0.00	1.0	N	238	42	2	8.6	1.0	0.5	0.00	0.0	1.0	11.10	0.0	0.00
1	2	2023-03-01 00:08:25	2023-03-01 00:39:30	2.0	12.40	1.0	N	138	231	1	52.7	6.0	0.5	12.54	0.0	1.0	76.49	2.5	1.25
2	1	2023-03-01 00:15:04	2023-03-01 00:29:26	0.0	3.30	1.0	N	140	186	1	18.4	3.5	0.5	4.65	0.0	1.0	28.05	2.5	0.00
3	1	2023-03-01 00:49:37	2023-03-01 01:01:05	1.0	2.90	1.0	N	140	43	1	15.6	3.5	0.5	4.10	0.0	1.0	24.70	2.5	0.00
4	2	2023-03-01 00:08:04	2023-03-01 00:11:06	1.0	1.23	1.0	N	79	137	1	7.2	1.0	0.5	2.44	0.0	1.0	14.64	2.5	0.00

abril.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3288250 entries, 0 to 3288249
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 439.0+ MB

abril.head()

VendorID	tpep_pickup_datetime	tpep_dropoff_datetime	passenger_count	trip_distance	RatecodeID	store_and_fwd_flag	PULocationID	DOLocationID	payment_type	fare_amount	extra	mta_tax	tip_amount	tolls_amount	improvement_surcharge	total_amount	congestion_surcharge	Airport_fee
0	1	2023-04-01 00:14:49	2023-04-01 00:45:01	2.0	4.90	1.0	N	48	223	1	28.9	3.5	0.5	6.0	0.00	1.0	39.9	2.5	0.00
1	2	2023-04-01 00:00:24	2023-04-01 00:56:19	1.0	21.89	2.0	N	132	43	2	70.0	0.0	0.5	0.0	6.55	1.0	81.8	2.5	1.25
2	1	2023-04-01 00:03:50	2023-04-01 00:14:42	2.0	1.30	1.0	N	148	113	1	11.4	3.5	0.5	2.0	0.00	1.0	18.4	2.5	0.00
3	1	2023-04-01 00:53:18	2023-04-01 01:01:28	1.0	1.50	1.0	N	249	79	1	10.0	3.5	0.5	1.0	0.00	1.0	16.0	2.5	0.00
4	2	2023-04-01 00:07:00	2023-04-01 00:17:16	2.0	1.49	1.0	N	158	246	1	11.4	1.0	0.5	1.0	0.00	1.0	17.4	2.5	0.00

mayo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3513649 entries, 0 to 3513648
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 469.1+ MB

mayo.head()

VendorID	tpep_pickup_datetime	tpep_dropoff_datetime	passenger_count	trip_distance	RatecodeID	store_and_fwd_flag	PULocationID	DOLocationID	payment_type	fare_amount	extra	mta_tax	tip_amount	tolls_amount	improvement_surcharge	total_amount	congestion_surcharge	Airport_fee
0	1	2023-05-01 00:33:13	2023-05-01 00:53:01	0.0	7.80	1.0	N	138	43	1	33.8	7.75	0.5	8.60	0.00	1.0	51.65	0.0	1.75
1	1	2023-05-01 00:42:49	2023-05-01 01:11:18	2.0	8.10	1.0	N	138	262	1	35.9	10.25	0.5	9.50	0.00	1.0	57.15	2.5	1.75
2	1	2023-05-01 00:56:34	2023-05-01 01:13:39	2.0	9.10	1.0	N	138	141	1	35.2	10.25	0.5	10.70	6.55	1.0	64.20	2.5	1.75
3	2	2023-05-01 00:00:52	2023-05-01 00:20:12	1.0	8.21	1.0	N	138	140	1	33.1	6.00	0.5	2.24	0.00	1.0	47.09	2.5	1.75
4	1	2023-05-01 00:05:50	2023-05-01 00:19:41	0.0	7.90	1.0	N	138	263	1	31.0	10.25	0.5	9.85	6.55	1.0	59.15	2.5	1.75

junio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3307234 entries, 0 to 3307233
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 441.6+ MB

junio.head()

VendorID	tpep_pickup_datetime	tpep_dropoff_datetime	passenger_count	trip_distance	RatecodeID	store_and_fwd_flag	PULocationID	DOLocationID	payment_type	fare_amount	extra	mta_tax	tip_amount	tolls_amount	improvement_surcharge	total_amount	congestion_surcharge	Airport_fee
0	1	2023-06-01 00:08:48	2023-06-01 00:29:41	1.0	3.40	1.0	N	140	238	1	21.9	3.50	0.5	6.70	0.0	1.0	33.60	2.5	0.00
1	1	2023-06-01 00:15:04	2023-06-01 00:25:18	0.0	3.40	1.0	N	50	151	1	15.6	3.50	0.5	3.00	0.0	1.0	23.60	2.5	0.00
2	1	2023-06-01 00:48:24	2023-06-01 01:07:07	1.0	10.20	1.0	N	138	97	1	40.8	7.75	0.5	10.00	0.0	1.0	60.05	0.0	1.75
3	2	2023-06-01 00:54:03	2023-06-01 01:17:29	3.0	9.83	1.0	N	100	244	1	39.4	1.00	0.5	8.88	0.0	1.0	53.28	2.5	0.00
4	2	2023-06-01 00:18:44	2023-06-01 00:27:18	1.0	1.17	1.0	N	137	234	1	9.3	1.00	0.5	0.72	0.0	1.0	15.02	2.5	0.00

julio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2907108 entries, 0 to 2907107
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 388.1+ MB

julio.head()

VendorID	tpep_pickup_datetime	tpep_dropoff_datetime	passenger_count	trip_distance	RatecodeID	store_and_fwd_flag	PULocationID	DOLocationID	payment_type	fare_amount	extra	mta_tax	tip_amount	tolls_amount	improvement_surcharge	total_amount	congestion_surcharge	Airport_fee
0	1	2023-07-01 00:29:59	2023-07-01 00:40:15	1.0	1.80	1.0	N	140	263	1	12.1	3.5	0.5	5.10	0.0	1.0	22.20	2.5	0.0
1	2	2023-07-01 00:03:25	2023-07-01 00:23:44	1.0	2.31	1.0	N	163	163	2	19.1	1.0	0.5	0.00	0.0	1.0	24.10	2.5	0.0
2	2	2023-07-01 00:38:29	2023-07-01 00:48:53	1.0	2.36	1.0	N	142	262	1	13.5	1.0	0.5	3.70	0.0	1.0	22.20	2.5	0.0
3	2	2023-07-01 00:14:16	2023-07-01 00:29:13	1.0	4.36	1.0	N	68	24	1	19.8	1.0	0.5	4.96	0.0	1.0	29.76	2.5	0.0
4	1	2023-07-01 00:11:15	2023-07-01 00:20:47	0.0	1.60	1.0	N	161	107	1	11.4	3.5	0.5	3.25	0.0	1.0	19.65	2.5	0.0

agosto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2824209 entries, 0 to 2824208
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 377.1+ MB

agosto.head()

VendorID	tpep_pickup_datetime	tpep_dropoff_datetime	passenger_count	trip_distance	RatecodeID	store_and_fwd_flag	PULocationID	DOLocationID	payment_type	fare_amount	extra	mta_tax	tip_amount	tolls_amount	improvement_surcharge	total_amount	congestion_surcharge	Airport_fee
0	1	2023-08-01 00:26:44	2023-08-01 00:45:25	1.0	4.30	1.0	N	263	90	1	21.9	3.50	0.5	5.35	0.00	1.0	32.25	2.5	0.00
1	1	2023-08-01 00:55:42	2023-08-01 01:00:53	1.0	0.00	1.0	N	132	132	3	5.1	2.75	0.5	0.00	0.00	1.0	9.35	0.0	1.75
2	2	2023-08-01 00:32:04	2023-08-01 01:09:03	1.0	20.61	2.0	N	132	13	1	70.0	0.00	0.5	14.80	0.00	1.0	90.55	2.5	1.75
3	2	2023-08-01 00:13:37	2023-08-01 00:41:15	1.0	13.37	1.0	N	138	254	2	54.1	6.00	0.5	0.00	6.55	1.0	69.90	0.0	1.75
4	1	2023-08-01 00:24:46	2023-08-01 00:41:31	2.0	3.20	5.0	N	140	143	4	20.0	0.00	0.0	0.00	0.00	1.0	21.00	0.0	0.00

septiembre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2846722 entries, 0 to 2846721
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
dtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)
memory usage: 380.1+ MB

septiembre.head()

VendorID	tpep_pickup_datetime	tpep_dropoff_datetime	passenger_count	trip_distance	RatecodeID	store_and_fwd_flag	PULocationID	DOLocationID	payment_type	fare_amount	extra	mta_tax	tip_amount	tolls_amount	improvement_surcharge	total_amount	congestion_surcharge	Airport_fee
0	1	2023-09-01 00:15:37	2023-09-01 00:20:21	1.0	0.80	1.0	N	163	230	2	6.5	3.5	0.5	0.00	0.0	1.0	11.50	2.5	0.00
1	2	2023-09-01 00:18:40	2023-09-01 00:30:28	2.0	2.34	1.0	N	236	233	1	14.2	1.0	0.5	2.00	0.0	1.0	21.20	2.5	0.00
2	2	2023-09-01 00:35:01	2023-09-01 00:39:04	1.0	1.62	1.0	N	162	236	1	8.6	1.0	0.5	2.00	0.0	1.0	15.60	2.5	0.00
3	2	2023-09-01 00:45:45	2023-09-01 00:47:37	1.0	0.74	1.0	N	141	229	1	5.1	1.0	0.5	1.00	0.0	1.0	11.10	2.5	0.00
4	2	2023-09-01 00:01:23	2023-09-01 00:38:05	1.0	9.85	1.0	N	138	230	1	45.0	6.0	0.5	17.02	0.0	1.0	73.77	2.5	1.75

alt_fuel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 882 entries, 0 to 881
Data columns (total 22 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Category                            882 non-null    object
 1   Model                               882 non-null    object
 2   Model Year                          594 non-null    float64
 3   Manufacturer                        882 non-null    object
 4   Fuel                                882 non-null    object
 5   All-Electric Range                  222 non-null    float64
 6   PHEV Total Range                    43 non-null     float64
 7   Alternative Fuel Economy City       169 non-null    float64
 8   Alternative Fuel Economy Highway    169 non-null    float64
 9   Alternative Fuel Economy Combined   262 non-null    float64
 10  Conventional Fuel Economy City      444 non-null    float64
 11  Conventional Fuel Economy Highway   444 non-null    float64
 12  Conventional Fuel Economy Combined  444 non-null    float64
 13  Transmission Type                   640 non-null    object
 14  Transmission Make                   125 non-null    object
 15  Engine Type                         589 non-null    object
 16  Engine Size                         589 non-null    object
 17  Engine Cylinder Count               449 non-null    float64
 18  Number of Passengers                121 non-null    object
 19  Heavy-Duty Power System             245 non-null    object
 20  Notes                               179 non-null    object
 21  Drivetrain                          329 non-null    object
dtypes: float64(10), object(12)
memory usage: 151.7+ KB

alt_fuel.head()

Category	Model	Model Year	Manufacturer	Fuel	All-Electric Range	PHEV Total Range	Alternative Fuel Economy City	Alternative Fuel Economy Highway	Alternative Fuel Economy Combined	Conventional Fuel Economy City	Conventional Fuel Economy Highway	Conventional Fuel Economy Combined	Transmission Type	Transmission Make	Engine Type	Engine Size	Engine Cylinder Count	Number of Passengers	Heavy-Duty Power System	Notes	Drivetrain
0	Sedan/Wagon	NSX	2022.0	Acura	Hybrid Electric	NaN	NaN	NaN	NaN	NaN	21.0	22.0	21.0	Auto	NaN	SI	3.5L	6.0	NaN	NaN	NaN	AWD
1	Sedan/Wagon	A3	2022.0	Audi	Hybrid Electric	NaN	NaN	NaN	NaN	NaN	29.0	38.0	32.0	Auto	NaN	SI	2.0L	4.0	NaN	NaN	NaN	FWD
2	Sedan/Wagon	A3 quattro	2022.0	Audi	Hybrid Electric	NaN	NaN	NaN	NaN	NaN	28.0	36.0	31.0	Auto	NaN	SI	2.0L	4.0	NaN	NaN	NaN	AWD
3	Sedan/Wagon	A4 allroad quattro	2022.0	Audi	Hybrid Electric	NaN	NaN	NaN	NaN	NaN	24.0	30.0	26.0	Auto	NaN	SI	2.0L	4.0	NaN	NaN	NaN	AWD
4	Sedan/Wagon	A4 quattro	2022.0	Audi	Hybrid Electric	NaN	NaN	NaN	NaN	NaN	26.0	34.0	29.0	Auto	NaN	SI	2.0L	4.0	NaN	NaN	NaN	AWD

elec_alt_fuel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70406 entries, 0 to 70405
Data columns (total 65 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Fuel Type Code                    70406 non-null  object
 1   Station Name                      70406 non-null  object
 2   Street Address                    70405 non-null  object
 3   Intersection Directions           4493 non-null   object
 4   City                              70406 non-null  object
 5   State                             70406 non-null  object
 6   ZIP                               70405 non-null  object
 7   Plus4                             0 non-null      float64
 8   Station Phone                     65204 non-null  object
 9   Status Code                       70406 non-null  object
 10  Expected Date                     1218 non-null   object
 11  Groups With Access Code           70406 non-null  object
 12  Access Days Time                  66628 non-null  object
 13  Cards Accepted                    11289 non-null  object
 14  BD Blends                         1217 non-null   object
 15  NG Fill Type Code                 1603 non-null   object
 16  NG PSI                            1597 non-null   object
 17  EV Level1 EVSE Num                286 non-null    float64
 18  EV Level2 EVSE Num                54144 non-null  float64
 19  EV DC Fast Count                  8307 non-null   float64
 20  EV Other Info                     49 non-null     object
 21  EV Network                        60907 non-null  object
 22  EV Network Web                    50305 non-null  object
 23  Geocode Status                    70391 non-null  object
 24  Latitude                          70406 non-null  float64
 25  Longitude                         70406 non-null  float64
 26  Date Last Confirmed               70188 non-null  object
 27  ID                                70406 non-null  int64
 28  Updated At                        70406 non-null  object
 29  Owner Type Code                   30190 non-null  object
 30  Federal Agency ID                 955 non-null    float64
 31  Federal Agency Name               955 non-null    object
 32  Open Date                         69310 non-null  object
 33  Hydrogen Status Link              83 non-null     object
 34  NG Vehicle Class                  1780 non-null   object
 35  LPG Primary                       1867 non-null   object
 36  E85 Blender Pump                  4508 non-null   object
 37  EV Connector Types                60690 non-null  object
 38  Country                           70406 non-null  object
 39  Intersection Directions (French)  188 non-null    object
 40  Access Days Time (French)         6591 non-null   object
 41  BD Blends (French)                2 non-null      object
 42  Groups With Access Code (French)  70406 non-null  object
 43  Hydrogen Is Retail                117 non-null    object
 44  Access Code                       70406 non-null  object
 45  Access Detail Code                7423 non-null   object
 46  Federal Agency Code               955 non-null    object
 47  Facility Type                     27665 non-null  object
 48  CNG Dispenser Num                 1039 non-null   float64
 49  CNG On-Site Renewable Source      716 non-null    object
 50  CNG Total Compression Capacity    708 non-null    float64
 51  CNG Storage Capacity              357 non-null    float64
 52  LNG On-Site Renewable Source      62 non-null     object
 53  E85 Other Ethanol Blends          1458 non-null   object
 54  EV Pricing                        16961 non-null  object
 55  EV Pricing (French)               2032 non-null   object
 56  LPG Nozzle Types                  1826 non-null   object
 57  Hydrogen Pressures                116 non-null    object
 58  Hydrogen Standards                116 non-null    object
 59  CNG Fill Type Code                1603 non-null   object
 60  CNG PSI                           1597 non-null   object
 61  CNG Vehicle Class                 1622 non-null   object
 62  LNG Vehicle Class                 158 non-null    object
 63  EV On-Site Renewable Source       370 non-null    object
 64  Restricted Access                 53435 non-null  object
dtypes: float64(10), int64(1), object(54)
memory usage: 34.9+ MB

elec_alt_fuel.head()

Fuel Type Code	Station Name	Street Address	Intersection Directions	City	State	ZIP	Plus4	Station Phone	Status Code	Expected Date	Groups With Access Code	Access Days Time	Cards Accepted	BD Blends	NG Fill Type Code	NG PSI	EV Level1 EVSE Num	EV Level2 EVSE Num	EV DC Fast Count	EV Other Info	EV Network	EV Network Web	Geocode Status	Latitude	Longitude	Date Last Confirmed	ID	Updated At	Owner Type Code	Federal Agency ID	Federal Agency Name	Open Date	Hydrogen Status Link	NG Vehicle Class	LPG Primary	E85 Blender Pump	EV Connector Types	Country	Intersection Directions (French)	Access Days Time (French)	BD Blends (French)	Groups With Access Code (French)	Hydrogen Is Retail	Access Code	Access Detail Code	Federal Agency Code	Facility Type	CNG Dispenser Num	CNG On-Site Renewable Source	CNG Total Compression Capacity	CNG Storage Capacity	LNG On-Site Renewable Source	E85 Other Ethanol Blends	EV Pricing	EV Pricing (French)	LPG Nozzle Types	Hydrogen Pressures	Hydrogen Standards	CNG Fill Type Code	CNG PSI	CNG Vehicle Class	LNG Vehicle Class	EV On-Site Renewable Source	Restricted Access
0	CNG	Spire - Montgomery Operations Center	2951 Chestnut St	NaN	Montgomery	AL	36107	NaN	NaN	E	NaN	Private	NaN	NaN	NaN	B	3600	NaN	NaN	NaN	NaN	NaN	NaN	200-9	32.367916	-86.267021	2022-06-14	17	2022-06-14 16:22:47 UTC	T	NaN	NaN	2010-12-01	NaN	MD	NaN	NaN	NaN	US	NaN	NaN	NaN	Privé	NaN	private	NaN	NaN	STANDALONE_STATION	NaN	NONE	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	B	3600	MD	NaN	NaN	NaN
1	CNG	PS Energy - Atlanta	340 Whitehall St	From I-7585 N, exit 91 to Central Ave, left on...	Atlanta	GA	30303	NaN	770-350-3000	E	NaN	Public - Card key at all times	24 hours daily	Comdata FleetOne FuelMan Voyager Wright_Exp	NaN	Q	3600	NaN	NaN	NaN	NaN	NaN	NaN	200-8	33.745843	-84.398837	2021-08-04	42	2022-02-10 19:42:29 UTC	P	NaN	NaN	1994-07-15	NaN	MD	NaN	NaN	NaN	US	NaN	NaN	NaN	Public - Carte-clé en tout temps	NaN	public	KEY_ALWAYS	NaN	STANDALONE_STATION	1.0	NaN	30.0	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	Q	3600	MD	NaN	NaN	False
2	CNG	Metropolitan Atlanta Rapid Transit Authority	2424 Piedmont Rd NE	NaN	Atlanta	GA	30324	NaN	NaN	E	NaN	Private - Government only	NaN	NaN	NaN	Q	3000	NaN	NaN	NaN	NaN	NaN	NaN	200-8	33.821911	-84.367461	2021-08-04	45	2022-02-10 19:42:29 UTC	LG	NaN	NaN	1996-12-15	NaN	LD	NaN	NaN	NaN	US	NaN	NaN	NaN	Privé - Réservé au gouvernement	NaN	private	GOVERNMENT	NaN	FLEET_GARAGE	NaN	NaN	30.0	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	Q	3000	LD	NaN	NaN	NaN
3	CNG	United Parcel Service	270 Marvin Miller Dr	NaN	Atlanta	GA	30336	NaN	NaN	E	NaN	Private	NaN	NaN	NaN	B	3600	NaN	NaN	NaN	NaN	NaN	NaN	200-9	33.760256	-84.543822	2022-06-14	64	2022-06-14 16:22:47 UTC	P	NaN	NaN	1997-01-01	NaN	HD	NaN	NaN	NaN	US	NaN	NaN	NaN	Privé	NaN	private	NaN	NaN	STANDALONE_STATION	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	B	3600	HD	NaN	NaN	NaN
4	CNG	Arkansas Oklahoma Gas Corp	2100 S Waldron Rd	NaN	Fort Smith	AR	72903	NaN	479-783-3188	E	NaN	Public - Credit card at all times	24 hours daily	FuelMan M V Wright_Exp	NaN	Q	3600	NaN	NaN	NaN	NaN	NaN	NaN	200-9	35.362213	-94.375338	2022-06-14	73	2022-06-14 16:22:47 UTC	T	NaN	NaN	1997-01-01	NaN	MD	NaN	NaN	NaN	US	NaN	NaN	NaN	Public - Carte de crédit en tout temps	NaN	public	CREDIT_CARD_ALWAYS	NaN	UTILITY	1.0	NONE	250.0	57855.0	NaN	NaN	NaN	NaN	NaN	NaN	NaN	Q	3600	MD	NaN	NaN	False

elec_car_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Brand            103 non-null    object
 1   Model            103 non-null    object
 2   AccelSec         103 non-null    float64
 3   TopSpeed_KmH     103 non-null    int64
 4   Range_Km         103 non-null    int64
 5   Efficiency_WhKm  103 non-null    int64
 6   FastCharge_KmH   103 non-null    object
 7   RapidCharge      103 non-null    object
 8   PowerTrain       103 non-null    object
 9   PlugType         103 non-null    object
 10  BodyStyle        103 non-null    object
 11  Segment          103 non-null    object
 12  Seats            103 non-null    int64
 13  PriceEuro        103 non-null    int64
dtypes: float64(1), int64(5), object(8)
memory usage: 11.4+ KB

elec_car_clean.head()

Brand	Model	AccelSec	TopSpeed_KmH	Range_Km	Efficiency_WhKm	FastCharge_KmH	RapidCharge	PowerTrain	PlugType	BodyStyle	Segment	Seats	PriceEuro
0	Tesla	Model 3 Long Range Dual Motor	4.6	233	450	161	940	Yes	AWD	Type 2 CCS	Sedan	D	5	55480
1	Volkswagen	ID.3 Pure	10.0	160	270	167	250	Yes	RWD	Type 2 CCS	Hatchback	C	5	30000
2	Polestar	2	4.7	210	400	181	620	Yes	AWD	Type 2 CCS	Liftback	D	5	56440
3	BMW	iX3	6.8	180	360	206	560	Yes	RWD	Type 2 CCS	SUV	D	5	68040
4	Honda	e	9.5	145	170	168	190	Yes	RWD	Type 2 CCS	Hatchback	B	4	32997

elec_car_norm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Brand        103 non-null    object
 1   Model        103 non-null    object
 2   Accel        103 non-null    object
 3   TopSpeed     103 non-null    object
 4   Range        103 non-null    object
 5   Efficiency   103 non-null    object
 6   FastCharge   103 non-null    object
 7   RapidCharge  103 non-null    object
 8   PowerTrain   103 non-null    object
 9   PlugType     103 non-null    object
 10  BodyStyle    103 non-null    object
 11  Segment      103 non-null    object
 12  Seats        103 non-null    int64
 13  PriceEuro    103 non-null    int64
dtypes: int64(2), object(12)
memory usage: 11.4+ KB

elec_car_norm.head()

	Brand	Model	Accel	TopSpeed	Range	Efficiency	FastCharge	RapidCharge	PowerTrain	PlugType	BodyStyle	Segment	Seats	PriceEuro
0	Tesla	Model 3 Long Range Dual Motor	4.6 sec	233 km/h	450 km	161 Wh/km	940 km/h	Rapid charging possible	All Wheel Drive	Type 2 CCS	Sedan	D	5	55480
1	Volkswagen	ID.3 Pure	10.0 sec	160 km/h	270 km	167 Wh/km	250 km/h	Rapid charging possible	Rear Wheel Drive	Type 2 CCS	Hatchback	C	5	30000
2	Polestar	2	4.7 sec	210 km/h	400 km	181 Wh/km	620 km/h	Rapid charging possible	All Wheel Drive	Type 2 CCS	Liftback	D	5	56440
3	BMW	iX3	6.8 sec	180 km/h	360 km	206 Wh/km	560 km/h	Rapid charging possible	Rear Wheel Drive	Type 2 CCS	SUV	D	5	68040
4	Honda	e	9.5 sec	145 km/h	170 km	168 Wh/km	190 km/h	Rapid charging possible	Rear Wheel Drive	Type 2 CCS	Hatchback	B	4	32997

light_duty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3008 entries, 0 to 3007
Data columns (total 29 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Vehicle ID                          3008 non-null   int64
 1   Fuel ID                             3008 non-null   int64
 2   Fuel Configuration ID               2973 non-null   float64
 3   Manufacturer ID                     3008 non-null   int64
 4   Category ID                         3008 non-null   int64
 5   Model                               3008 non-null   object
 6   Model Year                          3008 non-null   int64
 7   Alternative Fuel Economy City       1595 non-null   float64
 8   Alternative Fuel Economy Highway    1505 non-null   float64
 9   Alternative Fuel Economy Combined   467 non-null    float64
 10  Conventional Fuel Economy City      2044 non-null   float64
 11  Conventional Fuel Economy Highway   2046 non-null   float64
 12  Conventional Fuel Economy Combined  763 non-null    float64
 13  Transmission Type                   2924 non-null   object
 14  Engine Type                         2211 non-null   object
 15  Engine Size                         2874 non-null   object
 16  Engine Cylinder Count               2443 non-null   float64
 17  Engine Description                  1971 non-null   object
 18  Manufacturer                        3008 non-null   object
 19  Manufacturer URL                    2844 non-null   object
 20  Category                            3008 non-null   object
 21  Fuel Code                           3008 non-null   object
 22  Fuel                                3008 non-null   object
 23  Fuel Configuration Name             2973 non-null   object
 24  Electric-Only Range                 374 non-null    float64
 25  PHEV Total Range                    43 non-null     float64
 26  PHEV Type                           176 non-null    object
 27  Notes                               73 non-null     object
 28  Drivetrain                          329 non-null    object
dtypes: float64(10), int64(5), object(14)
memory usage: 681.6+ KB

light_duty.head()

Vehicle ID	Fuel ID	Fuel Configuration ID	Manufacturer ID	Category ID	Model	Model Year	Alternative Fuel Economy City	Alternative Fuel Economy Highway	Alternative Fuel Economy Combined	Conventional Fuel Economy City	Conventional Fuel Economy Highway	Conventional Fuel Economy Combined	Transmission Type	Engine Type	Engine Size	Engine Cylinder Count	Engine Description	Manufacturer	Manufacturer URL	Category	Fuel Code	Fuel	Fuel Configuration Name	Electric-Only Range	PHEV Total Range	PHEV Type	Notes	Drivetrain
0	13044	45	9.0	365	27	NSX	2022	NaN	NaN	NaN	21.0	22.0	21.0	Auto	SI	3.5L	6.0	3.5L V6	Acura	http://www.acura.com/	Sedan/Wagon	HYBR	Hybrid Electric	Hybrid Electric	NaN	NaN	NaN	NaN	AWD
1	12854	45	9.0	377	27	A3	2022	NaN	NaN	NaN	29.0	38.0	32.0	Auto	SI	2.0L	4.0	2.0L I4	Audi	http://progress.audiusa.com/	Sedan/Wagon	HYBR	Hybrid Electric	Hybrid Electric	NaN	NaN	NaN	NaN	FWD
2	12842	45	9.0	377	27	A3 quattro	2022	NaN	NaN	NaN	28.0	36.0	31.0	Auto	SI	2.0L	4.0	2.0L I4	Audi	http://progress.audiusa.com/	Sedan/Wagon	HYBR	Hybrid Electric	Hybrid Electric	NaN	NaN	NaN	NaN	AWD
3	12783	45	9.0	377	27	A4 allroad quattro	2022	NaN	NaN	NaN	24.0	30.0	26.0	Auto	SI	2.0L	4.0	2.0L I4	Audi	http://progress.audiusa.com/	Sedan/Wagon	HYBR	Hybrid Electric	Hybrid Electric	NaN	NaN	NaN	NaN	AWD
4	12782	45	9.0	377	27	A4 quattro	2022	NaN	NaN	NaN	26.0	34.0	29.0	Auto	SI	2.0L	4.0	2.0L I4	Audi	http://progress.audiusa.com/	Sedan/Wagon	HYBR	Hybrid Electric	Hybrid Electric	NaN	NaN	NaN	NaN	AWD

vihicle_fuel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3008 entries, 0 to 3007
Data columns (total 29 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Vehicle ID                          3008 non-null   int64
 1   Fuel ID                             3008 non-null   int64
 2   Fuel Configuration ID               2973 non-null   float64
 3   Manufacturer ID                     3008 non-null   int64
 4   Category ID                         3008 non-null   int64
 5   Model                               3008 non-null   object
 6   Model Year                          3008 non-null   int64
 7   Alternative Fuel Economy City       1595 non-null   float64
 8   Alternative Fuel Economy Highway    1505 non-null   float64
 9   Alternative Fuel Economy Combined   467 non-null    float64
 10  Conventional Fuel Economy City      2044 non-null   float64
 11  Conventional Fuel Economy Highway   2046 non-null   float64
 12  Conventional Fuel Economy Combined  763 non-null    float64
 13  Transmission Type                   2924 non-null   object
 14  Engine Type                         2211 non-null   object
 15  Engine Size                         2874 non-null   object
 16  Engine Cylinder Count               2443 non-null   float64
 17  Engine Description                  1971 non-null   object
 18  Manufacturer                        3008 non-null   object
 19  Manufacturer URL                    2844 non-null   object
 20  Category                            3008 non-null   object
 21  Fuel Code                           3008 non-null   object
 22  Fuel                                3008 non-null   object
 23  Fuel Configuration Name             2973 non-null   object
 24  Electric-Only Range                 374 non-null    float64
 25  PHEV Total Range                    43 non-null     float64
 26  PHEV Type                           176 non-null    object
 27  Notes                               73 non-null     object
 28  Drivetrain                          329 non-null    object
dtypes: float64(10), int64(5), object(14)
memory usage: 681.6+ KB

vihicle_fuel.head()

	Vehicle ID	Fuel ID	Fuel Configuration ID	Manufacturer ID	Category ID	Model	Model Year	Alternative Fuel Economy City	Alternative Fuel Economy Highway	Alternative Fuel Economy Combined	Conventional Fuel Economy City	Conventional Fuel Economy Highway	Conventional Fuel Economy Combined	Transmission Type	Engine Type	Engine Size	Engine Cylinder Count	Engine Description	Manufacturer	Manufacturer URL	Category	Fuel Code	Fuel	Fuel Configuration Name	Electric-Only Range	PHEV Total Range	PHEV Type	Notes	Drivetrain
0	13044	45	9.0	365	27	NSX	2022	NaN	NaN	NaN	21.0	22.0	21.0	Auto	SI	3.5L	6.0	3.5L V6	Acura	http://www.acura.com/	Sedan/Wagon	HYBR	Hybrid Electric	Hybrid Electric	NaN	NaN	NaN	NaN	AWD
1	12854	45	9.0	377	27	A3	2022	NaN	NaN	NaN	29.0	38.0	32.0	Auto	SI	2.0L	4.0	2.0L I4	Audi	http://progress.audiusa.com/	Sedan/Wagon	HYBR	Hybrid Electric	Hybrid Electric	NaN	NaN	NaN	NaN	FWD
2	12842	45	9.0	377	27	A3 quattro	2022	NaN	NaN	NaN	28.0	36.0	31.0	Auto	SI	2.0L	4.0	2.0L I4	Audi	http://progress.audiusa.com/	Sedan/Wagon	HYBR	Hybrid Electric	Hybrid Electric	NaN	NaN	NaN	NaN	AWD
3	12783	45	9.0	377	27	A4 allroad quattro	2022	NaN	NaN	NaN	24.0	30.0	26.0	Auto	SI	2.0L	4.0	2.0L I4	Audi	http://progress.audiusa.com/	Sedan/Wagon	HYBR	Hybrid Electric	Hybrid Electric	NaN	NaN	NaN	NaN	AWD
4	12782	45	9.0	377	27	A4 quattro	2022	NaN	NaN	NaN	26.0	34.0	29.0	Auto	SI	2.0L	4.0	2.0L I4	Audi	http://progress.audiusa.com/	Sedan/Wagon	HYBR	Hybrid Electric	Hybrid Electric	NaN	NaN	NaN	NaN	AWD

air_quality_ny.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11427 entries, 163 to 11591
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     11427 non-null  datetime64[ns]
 1   pm10                     11427 non-null  float32
 2   pm2_5                    11427 non-null  float32
 3   carbon_monoxide          11427 non-null  float32
 4   nitrogen_dioxide         11427 non-null  float32
 5   sulphur_dioxide          11427 non-null  float32
 6   ozone                    11427 non-null  float32
 7   uv_index                 11427 non-null  float32
 8   uv_index_clear_sky       11427 non-null  float32
 9   us_aqi                   11427 non-null  float32
 10  us_aqi_pm2_5             11427 non-null  float32
 11  us_aqi_pm10              11427 non-null  float32
 12  us_aqi_nitrogen_dioxide  11427 non-null  float32
 13  us_aqi_carbon_monoxide   11427 non-null  float32
 14  us_aqi_ozone             11427 non-null  float32
 15  us_aqi_sulphur_dioxide   11427 non-null  float32
dtypes: datetime64[ns](1), float32(15)
memory usage: 848.1 KB

air_quality_ny.head()

date	pm10	pm2_5	carbon_monoxide	nitrogen_dioxide	sulphur_dioxide	ozone	uv_index	uv_index_clear_sky	us_aqi	us_aqi_pm2_5	us_aqi_pm10	us_aqi_nitrogen_dioxide	us_aqi_carbon_monoxide	us_aqi_ozone	us_aqi_sulphur_dioxide
163	2022-08-05 00:00:00	39.500000	27.100000	295.0	63.099998	7.95	96.0	0.0	0.0	58.891846	58.891846	21.689392	31.077618	0.679147	23.519634	4.334787
164	2022-08-05 01:00:00	46.299999	31.900000	312.0	69.699997	7.90	83.0	0.0	0.0	59.459221	59.459221	22.034088	34.328209	0.716184	22.823902	4.307525
165	2022-08-05 02:00:00	41.599998	28.600000	336.0	79.000000	7.85	64.0	0.0	0.0	60.514187	60.514187	22.655300	38.908592	0.765298	21.567717	4.280262
166	2022-08-05 03:00:00	32.700001	22.600000	350.0	85.199997	7.55	46.0	0.0	0.0	61.524826	61.524826	23.231058	41.962173	0.827295	19.615801	4.116685
167	2022-08-05 04:00:00	29.799999	20.700001	333.0	80.449997	6.95	44.0	0.0	0.0	62.242908	62.242908	23.594696	39.622734	0.891707	17.200060	3.789531

climate_change_ny.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 691 entries, 0 to 690
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     691 non-null    datetime64[ns]
 1   temperature_2m_max       691 non-null    float32
 2   temperature_2m_min       691 non-null    float32
 3   temperature_2m_mean      691 non-null    float32
 4   precipitation_sum        691 non-null    float32
 5   shortwave_radiation_sum  691 non-null    float32
dtypes: datetime64[ns](1), float32(5)
memory usage: 19.0 KB

climate_change_ny.head()

	date	temperature_2m_max	temperature_2m_min	temperature_2m_mean	precipitation_sum	shortwave_radiation_sum
0	2022-01-01 05:00:00	11.5725	7.4225	9.605833	26.5	1.61
1	2022-01-02 05:00:00	13.6225	2.0225	9.101666	8.8	2.57
2	2022-01-03 05:00:00	1.6225	-4.7775	-1.579583	1.9	1.36
3	2022-01-04 05:00:00	0.6225	-6.5775	-3.119166	0.0	9.23
4	2022-01-05 05:00:00	6.9725	-2.1275	2.074583	0.3	3.19

'''

"\n\nLos dataframes son estos:\n\nenero.info()\n\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 3066766 entries, 0 to 3066765\nData columns (total 19 columns):\n #   Column                 Dtype\n---  ------                 -----\n 0   VendorID               int64\n 1   tpep_pickup_datetime   datetime64[ns]\n 2   tpep_dropoff_datetime  datetime64[ns]\n 3   passenger_count        float64\n 4   trip_distance          float64\n 5   RatecodeID             float64\n 6   store_and_fwd_flag     object\n 7   PULocationID           int64\n 8   DOLocationID           int64\n 9   payment_type           int64\n 10  fare_amount            float64\n 11  extra                  float64\n 12  mta_tax                float64\n 13  tip_amount             float64\n 14  tolls_amount           float64\n 15  improvement_surcharge  float64\n 16  total_amount           float64\n 17  congestion_surcharge   float64\n 18  airport_fee            float64\ndtypes: datetime64[ns](2), float64(12), int64(4), object(1)\nmemory usage: 444.6+ MB\n\nenero.head()\n\nVendorID\ttpep_pickup_datetime\ttpep_dropoff_datetime\tpassenger_count\ttrip_distance\tRatecodeID\tstore_and_fwd_flag\tPULocationID\tDOLocationID\tpayment_type\tfare_amount\textra\tmta_tax\ttip_amount\ttolls_amount\timprovement_surcharge\ttotal_amount\tcongestion_surcharge\tairport_fee\n0\t2\t2023-01-01 00:32:10\t2023-01-01 00:40:36\t1.0\t0.97\t1.0\tN\t161\t141\t2\t9.3\t1.00\t0.5\t0.00\t0.0\t1.0\t14.30\t2.5\t0.00\n1\t2\t2023-01-01 00:55:08\t2023-01-01 01:01:27\t1.0\t1.10\t1.0\tN\t43\t237\t1\t7.9\t1.00\t0.5\t4.00\t0.0\t1.0\t16.90\t2.5\t0.00\n2\t2\t2023-01-01 00:25:04\t2023-01-01 00:37:49\t1.0\t2.51\t1.0\tN\t48\t238\t1\t14.9\t1.00\t0.5\t15.00\t0.0\t1.0\t34.90\t2.5\t0.00\n3\t1\t2023-01-01 00:03:48\t2023-01-01 00:13:25\t0.0\t1.90\t1.0\tN\t138\t7\t1\t12.1\t7.25\t0.5\t0.00\t0.0\t1.0\t20.85\t0.0\t1.25\n4\t2\t2023-01-01 00:10:29\t2023-01-01 00:21:19\t1.0\t1.43\t1.0\tN\t107\t79\t1\t11.4\t1.00\t0.5\t3.28\t0.0\t1.0\t19.68\t2.5\t0.00\n\nfebrero.info()\n\n\nclass 'pandas.core.frame.DataFrame'>\nRangeIndex: 2913955 entries, 0 to 2913954\nData columns (total 19 columns):\n #   Column                 Dtype\n---  ------                 -----\n 0   VendorID               int32\n 1   tpep_pickup_datetime   datetime64[ns]\n 2   tpep_dropoff_datetime  datetime64[ns]\n 3   passenger_count        float64\n 4   trip_distance          float64\n 5   RatecodeID             float64\n 6   store_and_fwd_flag     object\n 7   PULocationID           int32\n 8   DOLocationID           int32\n 9   payment_type           int64\n 10  fare_amount            float64\n 11  extra                  float64\n 12  mta_tax                float64\n 13  tip_amount             float64\n 14  tolls_amount           float64\n 15  improvement_surcharge  float64\n 16  total_amount           float64\n 17  congestion_surcharge   float64\n 18  Airport_fee            float64\ndtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)\nmemory usage: 389.1+ MB\n\nfebrero.head()\n\nVendorID\ttpep_pickup_datetime\ttpep_dropoff_datetime\tpassenger_count\ttrip_distance\tRatecodeID\tstore_and_fwd_flag\tPULocationID\tDOLocationID\tpayment_type\tfare_amount\textra\tmta_tax\ttip_amount\ttolls_amount\timprovement_surcharge\ttotal_amount\tcongestion_surcharge\tAirport_fee\n0\t1\t2023-02-01 00:32:53\t2023-02-01 00:34:34\t2.0\t0.30\t1.0\tN\t142\t163\t2\t4.4\t3.50\t0.5\t0.0\t0.0\t1.0\t9.40\t2.5\t0.00\n1\t2\t2023-02-01 00:35:16\t2023-02-01 00:35:30\t1.0\t0.00\t1.0\tN\t71\t71\t4\t-3.0\t-1.00\t-0.5\t0.0\t0.0\t-1.0\t-5.50\t0.0\t0.00\n2\t2\t2023-02-01 00:35:16\t2023-02-01 00:35:30\t1.0\t0.00\t1.0\tN\t71\t71\t4\t3.0\t1.00\t0.5\t0.0\t0.0\t1.0\t5.50\t0.0\t0.00\n3\t1\t2023-02-01 00:29:33\t2023-02-01 01:01:38\t0.0\t18.80\t1.0\tN\t132\t26\t1\t70.9\t2.25\t0.5\t0.0\t0.0\t1.0\t74.65\t0.0\t1.25\n4\t2\t2023-02-01 00:12:28\t2023-02-01 00:25:46\t1.0\t3.22\t1.0\tN\t161\t145\t1\t17.0\t1.00\t0.5\t3.3\t0.0\t1.0\t25.30\t2.5\t0.00\n\nmarzo.info()\n\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 3403766 entries, 0 to 3403765\nData columns (total 19 columns):\n #   Column                 Dtype\n---  ------                 -----\n 0   VendorID               int32\n 1   tpep_pickup_datetime   datetime64[ns]\n 2   tpep_dropoff_datetime  datetime64[ns]\n 3   passenger_count        float64\n 4   trip_distance          float64\n 5   RatecodeID             float64\n 6   store_and_fwd_flag     object\n 7   PULocationID           int32\n 8   DOLocationID           int32\n 9   payment_type           int64\n 10  fare_amount            float64\n 11  extra                  float64\n 12  mta_tax                float64\n 13  tip_amount             float64\n 14  tolls_amount           float64\n 15  improvement_surcharge  float64\n 16  total_amount           float64\n 17  congestion_surcharge   float64\n 18  Airport_fee            float64\ndtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)\nmemory usage: 454.5+ MB\n\nmarzo.head()\n\nVendorID\ttpep_pickup_datetime\ttpep_dropoff_datetime\tpassenger_count\ttrip_distance\tRatecodeID\tstore_and_fwd_flag\tPULocationID\tDOLocationID\tpayment_type\tfare_amount\textra\tmta_tax\ttip_amount\ttolls_amount\timprovement_surcharge\ttotal_amount\tcongestion_surcharge\tAirport_fee\n0\t2\t2023-03-01 00:06:43\t2023-03-01 00:16:43\t1.0\t0.00\t1.0\tN\t238\t42\t2\t8.6\t1.0\t0.5\t0.00\t0.0\t1.0\t11.10\t0.0\t0.00\n1\t2\t2023-03-01 00:08:25\t2023-03-01 00:39:30\t2.0\t12.40\t1.0\tN\t138\t231\t1\t52.7\t6.0\t0.5\t12.54\t0.0\t1.0\t76.49\t2.5\t1.25\n2\t1\t2023-03-01 00:15:04\t2023-03-01 00:29:26\t0.0\t3.30\t1.0\tN\t140\t186\t1\t18.4\t3.5\t0.5\t4.65\t0.0\t1.0\t28.05\t2.5\t0.00\n3\t1\t2023-03-01 00:49:37\t2023-03-01 01:01:05\t1.0\t2.90\t1.0\tN\t140\t43\t1\t15.6\t3.5\t0.5\t4.10\t0.0\t1.0\t24.70\t2.5\t0.00\n4\t2\t2023-03-01 00:08:04\t2023-03-01 00:11:06\t1.0\t1.23\t1.0\tN\t79\t137\t1\t7.2\t1.0\t0.5\t2.44\t0.0\t1.0\t14.64\t2.5\t0.00\n\nabril.info()\n\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 3288250 entries, 0 to 3288249\nData columns (total 19 columns):\n #   Column                 Dtype\n---  ------                 -----\n 0   VendorID               int32\n 1   tpep_pickup_datetime   datetime64[ns]\n 2   tpep_dropoff_datetime  datetime64[ns]\n 3   passenger_count        float64\n 4   trip_distance          float64\n 5   RatecodeID             float64\n 6   store_and_fwd_flag     object\n 7   PULocationID           int32\n 8   DOLocationID           int32\n 9   payment_type           int64\n 10  fare_amount            float64\n 11  extra                  float64\n 12  mta_tax                float64\n 13  tip_amount             float64\n 14  tolls_amount           float64\n 15  improvement_surcharge  float64\n 16  total_amount           float64\n 17  congestion_surcharge   float64\n 18  Airport_fee            float64\ndtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)\nmemory usage: 439.0+ MB\n\nabril.head()\n\nVendorID\ttpep_pickup_datetime\ttpep_dropoff_datetime\tpassenger_count\ttrip_distance\tRatecodeID\tstore_and_fwd_flag\tPULocationID\tDOLocationID\tpayment_type\tfare_amount\textra\tmta_tax\ttip_amount\ttolls_amount\timprovement_surcharge\ttotal_amount\tcongestion_surcharge\tAirport_fee\n0\t1\t2023-04-01 00:14:49\t2023-04-01 00:45:01\t2.0\t4.90\t1.0\tN\t48\t223\t1\t28.9\t3.5\t0.5\t6.0\t0.00\t1.0\t39.9\t2.5\t0.00\n1\t2\t2023-04-01 00:00:24\t2023-04-01 00:56:19\t1.0\t21.89\t2.0\tN\t132\t43\t2\t70.0\t0.0\t0.5\t0.0\t6.55\t1.0\t81.8\t2.5\t1.25\n2\t1\t2023-04-01 00:03:50\t2023-04-01 00:14:42\t2.0\t1.30\t1.0\tN\t148\t113\t1\t11.4\t3.5\t0.5\t2.0\t0.00\t1.0\t18.4\t2.5\t0.00\n3\t1\t2023-04-01 00:53:18\t2023-04-01 01:01:28\t1.0\t1.50\t1.0\tN\t249\t79\t1\t10.0\t3.5\t0.5\t1.0\t0.00\t1.0\t16.0\t2.5\t0.00\n4\t2\t2023-04-01 00:07:00\t2023-04-01 00:17:16\t2.0\t1.49\t1.0\tN\t158\t246\t1\t11.4\t1.0\t0.5\t1.0\t0.00\t1.0\t17.4\t2.5\t0.00\n\nmayo.info()\n\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 3513649 entries, 0 to 3513648\nData columns (total 19 columns):\n #   Column                 Dtype\n---  ------                 -----\n 0   VendorID               int32\n 1   tpep_pickup_datetime   datetime64[ns]\n 2   tpep_dropoff_datetime  datetime64[ns]\n 3   passenger_count        float64\n 4   trip_distance          float64\n 5   RatecodeID             float64\n 6   store_and_fwd_flag     object\n 7   PULocationID           int32\n 8   DOLocationID           int32\n 9   payment_type           int64\n 10  fare_amount            float64\n 11  extra                  float64\n 12  mta_tax                float64\n 13  tip_amount             float64\n 14  tolls_amount           float64\n 15  improvement_surcharge  float64\n 16  total_amount           float64\n 17  congestion_surcharge   float64\n 18  Airport_fee            float64\ndtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)\nmemory usage: 469.1+ MB\n\nmayo.head()\n\nVendorID\ttpep_pickup_datetime\ttpep_dropoff_datetime\tpassenger_count\ttrip_distance\tRatecodeID\tstore_and_fwd_flag\tPULocationID\tDOLocationID\tpayment_type\tfare_amount\textra\tmta_tax\ttip_amount\ttolls_amount\timprovement_surcharge\ttotal_amount\tcongestion_surcharge\tAirport_fee\n0\t1\t2023-05-01 00:33:13\t2023-05-01 00:53:01\t0.0\t7.80\t1.0\tN\t138\t43\t1\t33.8\t7.75\t0.5\t8.60\t0.00\t1.0\t51.65\t0.0\t1.75\n1\t1\t2023-05-01 00:42:49\t2023-05-01 01:11:18\t2.0\t8.10\t1.0\tN\t138\t262\t1\t35.9\t10.25\t0.5\t9.50\t0.00\t1.0\t57.15\t2.5\t1.75\n2\t1\t2023-05-01 00:56:34\t2023-05-01 01:13:39\t2.0\t9.10\t1.0\tN\t138\t141\t1\t35.2\t10.25\t0.5\t10.70\t6.55\t1.0\t64.20\t2.5\t1.75\n3\t2\t2023-05-01 00:00:52\t2023-05-01 00:20:12\t1.0\t8.21\t1.0\tN\t138\t140\t1\t33.1\t6.00\t0.5\t2.24\t0.00\t1.0\t47.09\t2.5\t1.75\n4\t1\t2023-05-01 00:05:50\t2023-05-01 00:19:41\t0.0\t7.90\t1.0\tN\t138\t263\t1\t31.0\t10.25\t0.5\t9.85\t6.55\t1.0\t59.15\t2.5\t1.75\n\njunio.info()\n\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 3307234 entries, 0 to 3307233\nData columns (total 19 columns):\n #   Column                 Dtype\n---  ------                 -----\n 0   VendorID               int32\n 1   tpep_pickup_datetime   datetime64[ns]\n 2   tpep_dropoff_datetime  datetime64[ns]\n 3   passenger_count        float64\n 4   trip_distance          float64\n 5   RatecodeID             float64\n 6   store_and_fwd_flag     object\n 7   PULocationID           int32\n 8   DOLocationID           int32\n 9   payment_type           int64\n 10  fare_amount            float64\n 11  extra                  float64\n 12  mta_tax                float64\n 13  tip_amount             float64\n 14  tolls_amount           float64\n 15  improvement_surcharge  float64\n 16  total_amount           float64\n 17  congestion_surcharge   float64\n 18  Airport_fee            float64\ndtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)\nmemory usage: 441.6+ MB\n\njunio.head()\n\nVendorID\ttpep_pickup_datetime\ttpep_dropoff_datetime\tpassenger_count\ttrip_distance\tRatecodeID\tstore_and_fwd_flag\tPULocationID\tDOLocationID\tpayment_type\tfare_amount\textra\tmta_tax\ttip_amount\ttolls_amount\timprovement_surcharge\ttotal_amount\tcongestion_surcharge\tAirport_fee\n0\t1\t2023-06-01 00:08:48\t2023-06-01 00:29:41\t1.0\t3.40\t1.0\tN\t140\t238\t1\t21.9\t3.50\t0.5\t6.70\t0.0\t1.0\t33.60\t2.5\t0.00\n1\t1\t2023-06-01 00:15:04\t2023-06-01 00:25:18\t0.0\t3.40\t1.0\tN\t50\t151\t1\t15.6\t3.50\t0.5\t3.00\t0.0\t1.0\t23.60\t2.5\t0.00\n2\t1\t2023-06-01 00:48:24\t2023-06-01 01:07:07\t1.0\t10.20\t1.0\tN\t138\t97\t1\t40.8\t7.75\t0.5\t10.00\t0.0\t1.0\t60.05\t0.0\t1.75\n3\t2\t2023-06-01 00:54:03\t2023-06-01 01:17:29\t3.0\t9.83\t1.0\tN\t100\t244\t1\t39.4\t1.00\t0.5\t8.88\t0.0\t1.0\t53.28\t2.5\t0.00\n4\t2\t2023-06-01 00:18:44\t2023-06-01 00:27:18\t1.0\t1.17\t1.0\tN\t137\t234\t1\t9.3\t1.00\t0.5\t0.72\t0.0\t1.0\t15.02\t2.5\t0.00\n\njulio.info()\n\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 2907108 entries, 0 to 2907107\nData columns (total 19 columns):\n #   Column                 Dtype\n---  ------                 -----\n 0   VendorID               int32\n 1   tpep_pickup_datetime   datetime64[ns]\n 2   tpep_dropoff_datetime  datetime64[ns]\n 3   passenger_count        float64\n 4   trip_distance          float64\n 5   RatecodeID             float64\n 6   store_and_fwd_flag     object\n 7   PULocationID           int32\n 8   DOLocationID           int32\n 9   payment_type           int64\n 10  fare_amount            float64\n 11  extra                  float64\n 12  mta_tax                float64\n 13  tip_amount             float64\n 14  tolls_amount           float64\n 15  improvement_surcharge  float64\n 16  total_amount           float64\n 17  congestion_surcharge   float64\n 18  Airport_fee            float64\ndtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)\nmemory usage: 388.1+ MB\n\njulio.head()\n\nVendorID\ttpep_pickup_datetime\ttpep_dropoff_datetime\tpassenger_count\ttrip_distance\tRatecodeID\tstore_and_fwd_flag\tPULocationID\tDOLocationID\tpayment_type\tfare_amount\textra\tmta_tax\ttip_amount\ttolls_amount\timprovement_surcharge\ttotal_amount\tcongestion_surcharge\tAirport_fee\n0\t1\t2023-07-01 00:29:59\t2023-07-01 00:40:15\t1.0\t1.80\t1.0\tN\t140\t263\t1\t12.1\t3.5\t0.5\t5.10\t0.0\t1.0\t22.20\t2.5\t0.0\n1\t2\t2023-07-01 00:03:25\t2023-07-01 00:23:44\t1.0\t2.31\t1.0\tN\t163\t163\t2\t19.1\t1.0\t0.5\t0.00\t0.0\t1.0\t24.10\t2.5\t0.0\n2\t2\t2023-07-01 00:38:29\t2023-07-01 00:48:53\t1.0\t2.36\t1.0\tN\t142\t262\t1\t13.5\t1.0\t0.5\t3.70\t0.0\t1.0\t22.20\t2.5\t0.0\n3\t2\t2023-07-01 00:14:16\t2023-07-01 00:29:13\t1.0\t4.36\t1.0\tN\t68\t24\t1\t19.8\t1.0\t0.5\t4.96\t0.0\t1.0\t29.76\t2.5\t0.0\n4\t1\t2023-07-01 00:11:15\t2023-07-01 00:20:47\t0.0\t1.60\t1.0\tN\t161\t107\t1\t11.4\t3.5\t0.5\t3.25\t0.0\t1.0\t19.65\t2.5\t0.0\n\nagosto.info()\n\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 2824209 entries, 0 to 2824208\nData columns (total 19 columns):\n #   Column                 Dtype\n---  ------                 -----\n 0   VendorID               int32\n 1   tpep_pickup_datetime   datetime64[ns]\n 2   tpep_dropoff_datetime  datetime64[ns]\n 3   passenger_count        float64\n 4   trip_distance          float64\n 5   RatecodeID             float64\n 6   store_and_fwd_flag     object\n 7   PULocationID           int32\n 8   DOLocationID           int32\n 9   payment_type           int64\n 10  fare_amount            float64\n 11  extra                  float64\n 12  mta_tax                float64\n 13  tip_amount             float64\n 14  tolls_amount           float64\n 15  improvement_surcharge  float64\n 16  total_amount           float64\n 17  congestion_surcharge   float64\n 18  Airport_fee            float64\ndtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)\nmemory usage: 377.1+ MB\n\nagosto.head()\n\nVendorID\ttpep_pickup_datetime\ttpep_dropoff_datetime\tpassenger_count\ttrip_distance\tRatecodeID\tstore_and_fwd_flag\tPULocationID\tDOLocationID\tpayment_type\tfare_amount\textra\tmta_tax\ttip_amount\ttolls_amount\timprovement_surcharge\ttotal_amount\tcongestion_surcharge\tAirport_fee\n0\t1\t2023-08-01 00:26:44\t2023-08-01 00:45:25\t1.0\t4.30\t1.0\tN\t263\t90\t1\t21.9\t3.50\t0.5\t5.35\t0.00\t1.0\t32.25\t2.5\t0.00\n1\t1\t2023-08-01 00:55:42\t2023-08-01 01:00:53\t1.0\t0.00\t1.0\tN\t132\t132\t3\t5.1\t2.75\t0.5\t0.00\t0.00\t1.0\t9.35\t0.0\t1.75\n2\t2\t2023-08-01 00:32:04\t2023-08-01 01:09:03\t1.0\t20.61\t2.0\tN\t132\t13\t1\t70.0\t0.00\t0.5\t14.80\t0.00\t1.0\t90.55\t2.5\t1.75\n3\t2\t2023-08-01 00:13:37\t2023-08-01 00:41:15\t1.0\t13.37\t1.0\tN\t138\t254\t2\t54.1\t6.00\t0.5\t0.00\t6.55\t1.0\t69.90\t0.0\t1.75\n4\t1\t2023-08-01 00:24:46\t2023-08-01 00:41:31\t2.0\t3.20\t5.0\tN\t140\t143\t4\t20.0\t0.00\t0.0\t0.00\t0.00\t1.0\t21.00\t0.0\t0.00\n\nseptiembre.info()\n\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 2846722 entries, 0 to 2846721\nData columns (total 19 columns):\n #   Column                 Dtype\n---  ------                 -----\n 0   VendorID               int32\n 1   tpep_pickup_datetime   datetime64[ns]\n 2   tpep_dropoff_datetime  datetime64[ns]\n 3   passenger_count        float64\n 4   trip_distance          float64\n 5   RatecodeID             float64\n 6   store_and_fwd_flag     object\n 7   PULocationID           int32\n 8   DOLocationID           int32\n 9   payment_type           int64\n 10  fare_amount            float64\n 11  extra                  float64\n 12  mta_tax                float64\n 13  tip_amount             float64\n 14  tolls_amount           float64\n 15  improvement_surcharge  float64\n 16  total_amount           float64\n 17  congestion_surcharge   float64\n 18  Airport_fee            float64\ndtypes: datetime64[ns](2), float64(12), int32(3), int64(1), object(1)\nmemory usage: 380.1+ MB\n\nseptiembre.head()\n\nVendorID\ttpep_pickup_datetime\ttpep_dropoff_datetime\tpassenger_count\ttrip_distance\tRatecodeID\tstore_and_fwd_flag\tPULocationID\tDOLocationID\tpayment_type\tfare_amount\textra\tmta_tax\ttip_amount\ttolls_amount\timprovement_surcharge\ttotal_amount\tcongestion_surcharge\tAirport_fee\n0\t1\t2023-09-01 00:15:37\t2023-09-01 00:20:21\t1.0\t0.80\t1.0\tN\t163\t230\t2\t6.5\t3.5\t0.5\t0.00\t0.0\t1.0\t11.50\t2.5\t0.00\n1\t2\t2023-09-01 00:18:40\t2023-09-01 00:30:28\t2.0\t2.34\t1.0\tN\t236\t233\t1\t14.2\t1.0\t0.5\t2.00\t0.0\t1.0\t21.20\t2.5\t0.00\n2\t2\t2023-09-01 00:35:01\t2023-09-01 00:39:04\t1.0\t1.62\t1.0\tN\t162\t236\t1\t8.6\t1.0\t0.5\t2.00\t0.0\t1.0\t15.60\t2.5\t0.00\n3\t2\t2023-09-01 00:45:45\t2023-09-01 00:47:37\t1.0\t0.74\t1.0\tN\t141\t229\t1\t5.1\t1.0\t0.5\t1.00\t0.0\t1.0\t11.10\t2.5\t0.00\n4\t2\t2023-09-01 00:01:23\t2023-09-01 00:38:05\t1.0\t9.85\t1.0\tN\t138\t230\t1\t45.0\t6.0\t0.5\t17.02\t0.0\t1.0\t73.77\t2.5\t1.75\n\nalt_fuel.info()\n\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 882 entries, 0 to 881\nData columns (total 22 columns):\n #   Column                              Non-Null Count  Dtype\n---  ------                              --------------  -----\n 0   Category                            882 non-null    object\n 1   Model                               882 non-null    object\n 2   Model Year                          594 non-null    float64\n 3   Manufacturer                        882 non-null    object\n 4   Fuel                                882 non-null    object\n 5   All-Electric Range                  222 non-null    float64\n 6   PHEV Total Range                    43 non-null     float64\n 7   Alternative Fuel Economy City       169 non-null    float64\n 8   Alternative Fuel Economy Highway    169 non-null    float64\n 9   Alternative Fuel Economy Combined   262 non-null    float64\n 10  Conventional Fuel Economy City      444 non-null    float64\n 11  Conventional Fuel Economy Highway   444 non-null    float64\n 12  Conventional Fuel Economy Combined  444 non-null    float64\n 13  Transmission Type                   640 non-null    object\n 14  Transmission Make                   125 non-null    object\n 15  Engine Type                         589 non-null    object\n 16  Engine Size                         589 non-null    object\n 17  Engine Cylinder Count               449 non-null    float64\n 18  Number of Passengers                121 non-null    object\n 19  Heavy-Duty Power System             245 non-null    object\n 20  Notes                               179 non-null    object\n 21  Drivetrain                          329 non-null    object\ndtypes: float64(10), object(12)\nmemory usage: 151.7+ KB\n\nalt_fuel.head()\n\nCategory\tModel\tModel Year\tManufacturer\tFuel\tAll-Electric Range\tPHEV Total Range\tAlternative Fuel Economy City\tAlternative Fuel Economy Highway\tAlternative Fuel Economy Combined\tConventional Fuel Economy City\tConventional Fuel Economy Highway\tConventional Fuel Economy Combined\tTransmission Type\tTransmission Make\tEngine Type\tEngine Size\tEngine Cylinder Count\tNumber of Passengers\tHeavy-Duty Power System\tNotes\tDrivetrain\n0\tSedan/Wagon\tNSX\t2022.0\tAcura\tHybrid Electric\tNaN\tNaN\tNaN\